### ISSUE TITLE
Latest main branch builds missing

### ISSUE THREAD

**Issue by gittastic** [connectbot/connectbot#1003]
@kruton I notice that the recent merges into main branch are no longer resulting in builds being available in Github. The last build was on 29th July 2021.

Is this intentional or are the builds broken?

Many thanks for maintaining Connectbot. I use it frequently 👍

**Comment by kruton** [comment]
Thanks for pointing that out. The build server needed a Java upgrade.

**Comment by gittastic** [comment]
@kruton looks like the builds are missing again.

**Comment by gittastic** [comment]
@kruton i think builds from main branch are missing again 👍

**Comment by gittastic** [comment]
@kruton last commit to main didn't seem to publish a build
