### ISSUE TITLE
Integration of  postquantum-cryptos (Kyber,SPHINCS,MCELIECE etc.) 

### ISSUE THREAD

**Issue by z-ph0ria** [connectbot/connectbot#1114]
Because the work of https://github.com/open-quantum-safe/openssh and M$ own change to support Wireguard w/ new algo(s) (personally would'nt touch) at https://github.com/kudelskisecurity/pq-wireguard - would'nt it be time we got the new ciphers for clients to android too?

I'd love to see it.

Thx for the word!
Sincerely yours,
z

**Comment by kruton** [comment]
I'm open to having new PQC algorithms, but I don't really want to take on a native dependency to do it. The actual protocol would be done in https://github.com/connectbot/sshlib and in Java language.

**Comment by z-ph0ria** [comment]
https://github.com/open-quantum-safe/libssh

Here you are, in which needs this also; https://github.com/open-quantum-safe/liboqs

**Comment by z-ph0ria** [comment]
I've integrated it in a shell, thou i have modded the Kyber-algo & Delerethium-hs w/ API's - benches out the NIST's own.

**Comment by kruton** [comment]
That's not in Java which would mean taking a native code dependency to integrate it.

**Comment by z-ph0ria** [comment]
https://github.com/open-quantum-safe/liboqs-java

**Comment by z-ph0ria** [comment]
The libssh i can get java for,hold on...

**Comment by z-ph0ria** [comment]
Sorry could'nt find it, but there are "translators, like from the src below into go or python etc, below is written in c - iirc it's not that diff from java. Meanwhile, i can try helping you 'translate' the .c's to java. It's worth a try.

https://github.com/open-quantum-safe/libssh/archive/refs/tags/OQS-libssh-snapshot-2022-01.zip

**Comment by z-ph0ria** [comment]
https://www.mtsystems.com/
http://tech.novosoft-us.com/product_c2j.jsp
https://www.tangiblesoftwaresolutions.com/converters.html

- those are the one's i found, since you got the big one in java, the rest should be a medium-sized project. But we need a client for android now.

Q: are you using web-sockets (not thru gcm) with connectbot? 
(Havent looked at code)

Sincerely,
z

**Comment by kruton** [comment]
The liboqs-java is just a JNI wrapper of the native code, so it still imposes a native code dependency.

I think the only way that it could work for this project is to reimplement in Java language. Translation probably wouldn't work very well. And `sntrup761x25519-sha512@openssh.com` seems like the obvious choice which means implementing Streamlined NTRU Prime in pure Java.

**Comment by z-ph0ria** [comment]
Hope you could have a nice look into it!

Thanks!

**Comment by z-ph0ria** [comment]
https://github.com/antontutoveanu/crystals-kyber-javascript

This one might be in your interest also. J/s.

**Comment by VA1DER** [comment]
https://javadoc.io/doc/org.bouncycastle/bcprov-jdk15to18/1.75/org/bouncycastle/pqc/crypto/ntruprime/SNTRUPrimeParameters.html
