### ISSUE TITLE
Can't run local shell scripts

### ISSUE THREAD

**Issue by jidanni** [connectbot/connectbot#1201]
Doing 
> $0 file.sh

gives Permission Denied, here on Android 12.

Perhaps it is because the app only asks for media permissions, and not full file permissions?

I'm trying to run it on items I copied to /sdcard here on my unrooted Samsung.

Same problem with
> cat file.sh | $0

or even
> wc file.sh

https://play.google.com/store/apps/details?id=com.qamar.terminal can run scripts right out of the box, because it's got the right permission needed.

**Comment by gth** [comment]
You're reporting a permissions error inside your ssh session, to the SSH client software? I don't see how this could at all relate to the app.

**Comment by jidanni** [comment]
The session is with localhost.
Just me and my cellphone, inside a Faraday cage.

**Comment by gth** [comment]
Your permissions inside the operating system are determined by your user login and it's related access levels.

Unless there's a hidden feature set that I've totally missed, it's like asking your car why the gate won't open. Connectbot is only displaying the connection you requested. What happens after that is between you and your operating system - which in this case happens to be your phone, but the app behaviour is no different.

**Comment by jidanni** [comment]
You're right! I've got to clean up my $PATH.
```
$ sh file
/system/bin/sh: /vendor/bin/s
h: Permission denied
```
