### ISSUE TITLE
Installation failed - ConnectBot-git-v1.9.9-42-g8fa6d9fd-google

### ISSUE THREAD

**Issue by ShevT** [connectbot/connectbot#1294]
adb install ConnectBot-git-v1.9.9-42-g8fa6d9fd-google.apk
Performing Streamed Install
adb: failed to install ConnectBot-git-v1.9.9-42-g8fa6d9fd-google.apk: Failure [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]

**Comment by kruton** [comment]
Ah, thanks. I was reworking the signing infrastructure. Looks like I need to have it do a few more actions before signing.

**Comment by kruton** [comment]
I updated the signing method and replaced the APKs available in that release.
