### ISSUE TITLE
Closing a connection does not go back to main screen (on git-master-2015-08-14_15-47-46)

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#135]
When I close a single connection with the shell exit command on tablet (Nexus 9) the terminal screen stay open and a unique navigation tab is showed with the name of my ex-connection. The "Home" button in action bar is not displayed, so it impossible to go back to the connection screen.
When two connections are openned, closing a connection with exit cmd, the tab does not close.

This seems to be related to @jklein24 Tab addition.

Also, the tabs are centered and look weird and the "undescore" (selected tab) does not display until I change tab or swipe.

**Comment by jklein24** [comment]
> When I close a single connection with the shell exit command on tablet (Nexus 9) the terminal screen
> stay open and a unique navigation tab is showed with the name of my ex-connection. The "Home" 
> button in action bar is not displayed, so it impossible to go back to the connection screen.
> When two connections are openned, closing a connection with exit cmd, the tab does not close.

I'm trying to repro this, but no luck so far. Here's what I'm doing:
1) Open up two connections.
2) Use "exit" close one. That one is closed and only the other is shown with no tabs.
3) Use "exit" to close the other remaining terminal. Closes and goes back to the hostlist as expected.

> Also, the tabs are centered and look weird and the "undescore" (selected tab) does not display until I change tab or swipe.

I've seen this once or twice, but I'm having trouble getting it to happen consistently. Do you have a good repro? Otherwise I'll just keep digging to see if I can track something down.

**Comment by alescdb** [comment]
I think this has something to do with the "Close on disconnect" in the connection settings, I have FCs when I check this.
For the centered tab, I always have this, landscape and portrait as soon as I have more than one connection.

**Comment by jklein24** [comment]
I don't think the tab centering is really a bug. That's just the default positioning for tabs. I can move them over, though. "Close on disconnect" seems like a likely candidate. If I enable that for both of my hosts, I can repro the crash. Without it, everything seems normal.

**Comment by alescdb** [comment]
I'm not sure yet, but It seems the activity is completely locked (but no FC) only with an ssh connection with "Close on disconnect" checked.
Tabs should not be centered, usually they fill parent width.

**Comment by jklein24** [comment]
> I'm not sure yet, but It seems the activity is completely locked (but no FC) only with an ssh connection with "Close on disconnect" checked.

I think I tracked this down. It looks like there's a codepath a missed when trying to make sure all the disconnect listeners were triggered on the UI thread. I'll send out a PR shortly.

**Comment by jklein24** [comment]
It looks like the reason that the tabs are centered on Nexus 9 is:

https://android.googlesource.com/platform/frameworks/support.git/+/master/design/res/values-sw600dp/styles.xml

Default styles with minimum screen width of 600 dp is to center. I can change that, but is it really the right thing to do from a UX perspective if this is the default Material implementation? I do admit that it looks a bit weird with so much empty space around...

cc @bengolds

**Comment by alescdb** [comment]
I've never seen centered tabs like this :-)

ActionBar Tabs :
https://developer.android.com/guide/topics/ui/actionbar.html
Design Guidelines :
https://www.google.com/design/spec/components/tabs.html#tabs-usage

**Comment by jklein24** [comment]
There are several examples of the centered tabs on the material design guidelines you linked to there. The ActionMode tabs (and all the NavigationMode stuff) has been deprecated in favor of TabLayout and common navigation patterns. See the documentation for any tab-related functions on https://developer.android.com/reference/android/support/v7/app/ActionBar.html. 

Also keep in mind that the tabs are only visible on large screens. Even with tabGravity set to "fill", the tabs are centered with a max width smaller than what would fill up the whole width of a tablet in landscape. I still think setting tabMode to scrollable and aligning the start of the tabs with the start of the app title in the actionbar is a reasonable request, though. I've also noticed that the action bar is still holo style, which should probably be updated in the process.

**Comment by jklein24** [comment]
FWIW, it's pretty easy to get the tabs to align left if that's what we want in sw600dp too. Here's what is looks like:

![device-2015-08-20-111853](https://cloud.githubusercontent.com/assets/1393755/9391759/88ffca42-472d-11e5-8e4a-e595a62cec5c.png)

I'm still trying to track down why the indicator is being buggy, but haven't gotten too far. Digging into the TabLayout implementation more...

**Comment by jklein24** [comment]
https://github.com/connectbot/connectbot/pull/148 fixes the disappearing tab indicator. The bug has been fixed in the support library, but hasn't been released yet.

**Comment by kruton** [comment]
I'll leave this open until we update our support library version.

**Comment by jklein24** [comment]
Sent out https://github.com/connectbot/connectbot/pull/149 to align the tabs left because I agree it looks nicer.
