### ISSUE TITLE
update f-droid version

### ISSUE THREAD

**Issue by gilcu3** [connectbot/connectbot#1351]
Please update the f-droid version, which is still in the 1.9.9

**Comment by alxrdn** [comment]
@kruton are you planing to release 1.9.10 to f-droid channel?
thx

**Comment by kruton** [comment]
I don't have access to F-Droid.

**Comment by alxrdn** [comment]
Thank you for your answer.
So, who did push the previous versions? https://f-droid.org/en/packages/org.connectbot/

**Comment by kruton** [comment]
I'm not sure. ConnectBot existed before F-Droid, so they probably just used
ConnectBot as one of the first applications to fill their store.

**Comment by alxrdn** [comment]
Indeed it seems that the f-droid build is authored by f-droid contributors and version 1.9.10 should be coming: https://gitlab.com/fdroid/fdroiddata/-/commit/e79585aa17ec92ae4a5cff1f7d0fae9f1e4de5c0

**Comment by gilcu3** [comment]
Thx @alxrdn, closing this as fixed then.

**Comment by alxrdn** [comment]
Also @kruton it seems that the current gradle versioning strategy in Connectbot prevents f-droid from automatically picking new releases: see this https://gitlab.com/fdroid/fdroiddata/-/issues/3166#note_1718356484
I don't know if you can improve this, but just in case...
