### ISSUE TITLE
Persistent notification no longer working

### ISSUE THREAD

**Issue by gittastic** [connectbot/connectbot#1352]
## Bug description
The persistent notification no longer appears when connected to a host when using ConnectBot v1.9.10+.

## Steps to reproduce
1. Connect to a host
2. Note the notification no longer appears. It is also not possible to grant notification permissions in Android 14.

## Expected behavior
The persistent notification should appear when connected to a host.

## Android device
 - Device: Google Pixel 8 Pro
 - OS: Android 14 build UQ1A.240105.004
 - ConnectBot Version: 1.9.10

**Comment by gittastic** [comment]
Out of interest, does the persistent notification work for anyone else on 1.9.10?

**Comment by GaidinBDJ** [comment]
I get no notifications at all; not the persistent notification and not the bell notifications.   It's kind of a problem.

**Comment by gittastic** [comment]
The app doesn't appear to have notification permissions for Android 13+.

**Comment by dtgeorge** [comment]
Same issue here. Galaxy s23 ultra.
