### ISSUE TITLE
Alt key

### ISSUE THREAD

**Issue by trymeouteh** [connectbot/connectbot#1370]
## Is your feature request related to a problem? Please describe.
An alt key is not available

## Describe the solution you'd like
To add an alt key in the keyboard buttons row

## Describe alternatives you've considered
None

## Additional context
None

**Comment by jpduyx** [comment]
That would be great. In bash i often use alt . "alt+dot" to add the previous comnands last word to the current cursor position

**Comment by slowpeek** [comment]
> That would be great. In bash i often use alt . "alt+dot" to add the previous comnands last word to the current cursor position

There are also alt+f, alt+b to walk through words.

I dont get it why there is no Alt as of now. Like, WHY ??

**Comment by kruton** [comment]
Pressing "alt+f" on another (remote) terminal actually sends "Esc" "F". So if you want to do that, just press the Esc key and press F on the keyboard. Hope that helps.
