### ISSUE TITLE
Allow holding down arrow keys to repeatedly press

### ISSUE THREAD

**Issue by kruton** [connectbot/connectbot#144]
From a review on Google Play Store:
> Arrow key bar needs to stay on screen 3x longer. Esc key is broken, will add a character when pressing it when cursor is on a word. **Also, would like to be able to hold the arrow key down to move cursor quickly.**

Holding down the arrow keys to scroll quickly sounds like a good idea.

**Comment by kruton** [comment]
@alescdb if you're interested!

**Comment by alescdb** [comment]
I'm on it ! :-)

**Comment by alescdb** [comment]
It was harder than I initially thought because of HorizontalScrollView.
Done in PR #134.

If you do not wish to merge the HScroll keyboard and the keyboard repeater and/or you prefer having two different PR, please let me know.

**Comment by kruton** [comment]
Awesome, thanks. I haven't really looked at hscroll yet from a code point of view, but I like the concept. I'll try to get to reviewing tomorrow.

**Comment by jklein24** [comment]
Note that from a hard keyboard this already works (although it vibrates a bunch). It's just the soft key that's a problem.

**Comment by jklein24** [comment]
Actually, this was fixed by #134 like @alescdb noted above :-). I guess we just forgot to close it out.
