### ISSUE TITLE
Scrolling does not reset timer for the soft key bar

### ISSUE THREAD

**Issue by kruton** [connectbot/connectbot#150]
Scrolling the soft key bar does not reset the timer, so it will disappear when you're scrolling.

**Comment by kruton** [comment]
@alescdb I should have tested this during review :)

**Comment by alescdb** [comment]
Yep that why I increased the autohide timeout :-)
I'll try to implement a onTouchEvent but they may be a conflict with repeatable keys.
Also when using the last git-master-release on Marshmallow preview 3, repeatable keys have a strange behaviour in some circontances.

**Comment by wp9015362** [comment]
Probably related:

https://github.com/connectbot/connectbot/issues/159

Regards
