### ISSUE TITLE
FC while connecting on 4.3

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#151]
On latest git-master-release, on a Galaxy Nexus (stock 4.3) I got a FC while connecting to "local" (haven't tryed other type of connection) :

> E/AndroidRuntime(24324): FATAL EXCEPTION: Connection
> E/AndroidRuntime(24324): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "grantpt" referenced by "libcom_google_ase_Exec.so"...
> E/AndroidRuntime(24324): 	at java.lang.Runtime.loadLibrary(Runtime.java:361)
> E/AndroidRuntime(24324): 	at java.lang.System.loadLibrary(System.java:525)
> E/AndroidRuntime(24324): 	at com.google.ase.Exec.<clinit>(Exec.java:67)
> E/AndroidRuntime(24324): 	at org.connectbot.transport.Local.connect(Local.java:93)
> E/AndroidRuntime(24324): 	at org.connectbot.service.TerminalBridge$3.run(TerminalBridge.java:284)
> E/AndroidRuntime(24324): 	at java.lang.Thread.run(Thread.java:841)
> W/ActivityManager(  411):   Force finishing activity org.connectbot/.ConsoleActivity
> W/ActivityManager(  411):   Force finishing activity org.connectbot/.HostListActivity

**Comment by kruton** [comment]
Hm, that should never happen. `grantpt` has been in the Android NDK since the first release.

**Comment by kruton** [comment]
Ah, I see. Gradle is building for android-21 and the definition has changed from `__inline__` to non-`__inline__`.

**Comment by kruton** [comment]
Fixed by #156
