### ISSUE TITLE
Move special key bar above virtual keyboard

### ISSUE THREAD

**Issue by Jonny007-MKD** [connectbot/connectbot#158]
Hello, 

I am only using the virtual keyboard.
Is there a way for Connectbot to determine the height of the keyboard so that the bar with special keys (ESC, arrows) can be displayed above?
It would also be nice to automatically adjust the size of the terminal.

**Comment by jplitza** [comment]
I think the issue you are mentioning is a long-standing one that is related to the "fullscreen" setting. Do you have it enabled? If so, please disable it and see if the behavior is fixed.

**Comment by Jonny007-MKD** [comment]
Yes, this fixed it! Thank you!
I suppose there is no way to hide the Status bar and still have the keys above the keyboard, is it?
I think it would be nice if this issue would be mentioned in the description of the setting.

Am 29. August 2015 15:29:03 MESZ, schrieb Jan-Philipp Litza <notifications@github.com>:
