### ISSUE TITLE
Option for showing virtual keys permanently

### ISSUE THREAD

**Issue by jplitza** [connectbot/connectbot#159]
I like the new feature of having virtual arrow keys very much! That much, in fact, the I would love to have the bar show up at all times, not only when touching. That way, it would only take one touch to use the keys and I could look where to touch while typing other stuff without first having to touch the console.

**Comment by wp9015362** [comment]
+1

**Comment by wp9015362** [comment]
When the virtual keyboard would be displayed permanently, it's transparency should also be disabled IMHO.
