### ISSUE TITLE
Keyboard button on virtual keyboard does not close keyboard

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#164]
Hello,

the keyboard button on the virtual keyboard can be used to open the keyboard.

But when the keyboard is open and the keyboard button on the virtual keyboard is being pressed, then the keyboard does not close.

Would there be any chance you could fix that and make the keyboard button on the virtual keyboard a proper toggle to open and close the keyboard?

There would also be a proper [Material icon](https://github.com/connectbot/connectbot/issues/162) available for this, see the "ic_keyboard_hide" Material icon over there:

https://www.google.com/design/icons/#ic_keyboard_hide

If the keyboard is closed, the keyboard button on the virtual keyboard should use the ["ic_keyboard" Material icon](https://www.google.com/design/icons/#ic_keyboard) and should open the keyboard when being pressed.

And if the keyboard is open, the keyboard button on the virtual keyboard should use the ["ic_keyboard_hide" Material icon](https://www.google.com/design/icons/#ic_keyboard_hide) and should close the keyboard when being pressed.

Any chance you could do that?

Regards

**Comment by kruton** [comment]
There used to be no way to tell if the IME was open or not. I'm not sure if there is a way now. That's the reason why it only opens the keyboard since your state will get out of sync if you try to track it.

**Comment by wp9015362** [comment]
> @kruton wrote:
> 
> There used to be no way to tell if the IME was open or not. I'm not sure if there is a way now. That's the reason why it only opens the keyboard since your state will get out of sync if you try to track it.

Well, there's a plethora of results when searching for this topic on Google. It seems to be possible to detect if the IME is open, here are three of the search results for example:

http://stackoverflow.com/questions/2150078/how-to-check-visibility-of-software-keyboard-in-android
and:
http://toastdroid.com/2014/10/14/on-screen-keyboard-state-tracking-in-3-easy-steps/
and:
http://www.ninthavenue.com.au/how-to-check-if-the-software-keyboard-is-shown-in-android

Does any of that help to fix this issue?

Regards
