### ISSUE TITLE
ConnectBot theme (toolbar, status bar, accent color etc.) does not reflect colors of ConnectBot logo

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#167]
Hello,

currently the ConnectBot theme does not reflect the colors of the ConnectBot logo:

![Image](https://raw.githubusercontent.com/connectbot/connectbot/master/icons/icon64.png)

But I think it should.

Could you please make the ConnectBot theme (toolbar, status bar, accent color etc.) make reflect the colors of the ConnectBot logo, as described in the Google Material Design guidelines over there:

https://www.google.com/design/spec/style/color.html#color-ui-color-application

?

Regards

**Comment by kruton** [comment]
Started this in an upcoming pull request.
![material-cb](https://cloud.githubusercontent.com/assets/50407/9828802/c4fc995e-58a7-11e5-9468-2570736df577.png)

**Comment by wp9015362** [comment]
> @kruton commented in https://github.com/connectbot/connectbot/pull/198#issuecomment-139721913 :
> 
> @jklein24 @bengolds I'm going to submit this, but I'm open to color palette changes or whatever.

Thank you.

But (no offence):

You have set the primary/dark primary colors to cyan (#00BCD4 / #0097A7).

Cyan is not part of the ConnectBot logo/"brand".

The frame around the ConnectBot logo is rather light blue (which would also be available from the [Google Material Design Color Palette](https://www.google.com/design/spec/style/color.html#color-color-palette)).

But the light blue colors in the [Google Material Design Color Palette](https://www.google.com/design/spec/style/color.html#color-color-palette) also do not match the light blue color of the frame around the ConnectBot logo.

I have submitted an issue for it now, see:

https://github.com/connectbot/connectbot/issues/201

Also, you have set the accent color to deep orange (#F4511E).

Orange is not part of the ConnectBot logo/"brand" either and it does not go well with cyan IMHO (and also would not go well with light blue either IMHO).

The accent color should not be orange IMHO.

I also noticed that the green indicator in the host list, which shows that the host is connected is #99CC00.

#99CC00 is not part of the [Google Material Design Color Palette](https://www.google.com/design/spec/style/color.html#color-color-palette).

Maybe it would make sense to make that indicator use a green color (connected) and red color (disconnected) which is part of the [Google Material Design Color Palette](https://www.google.com/design/spec/style/color.html#color-color-palette).

I've also submitted an issue for that now, see:

https://github.com/connectbot/connectbot/issues/202

Regards

**Comment by jklein24** [comment]
+cc @khorimoto

**Comment by jklein24** [comment]
https://www.materialpalette.com/ is pretty helpful for this fyi

**Comment by khorimoto** [comment]
I'll take this on.

**Comment by jklein24** [comment]
Could also be a good starter bug for @rhansby

**Comment by wp9015362** [comment]
Shouldn't it be reopened then :wink:?

**Comment by wp9015362** [comment]
PS:

@khorimoto / @rhansby :

It would be nice if you could also add a light theme while being at it, as requested in:

https://github.com/connectbot/connectbot/issues/163

That would be much appreciated.

Regards

**Comment by rhansby** [comment]
I'm taking this instead of @khorimoto.

@wp9015362, what would you suggest instead for the accent color? (instead of the deep orange)

**Comment by wp9015362** [comment]
> @rhansby wrote:
> 
> @wp9015362, what would you suggest instead for the accent color? (instead of the deep orange). As I see it, deep orange is complimentary to cyan or light blue, making it a good choice.

Well, you might have a point in regards to the complementary color.

I played a bit around with some blue (blue and light blue) and orange (orange and deep orange) colors in [Amaze File Manager](https://github.com/arpitkh96/AmazeFileManager). In Amaze File Manager, the primary and accent colors can be configured by the user (it let's you choose between some specific predefined colors). As you can see, it suddenly all starts to look better once you look at it with a [light theme](https://github.com/connectbot/connectbot/issues/163) :wink:, some screenshots:

![Image](https://cloud.githubusercontent.com/assets/7558360/9920799/b0cd01b0-5cd7-11e5-81ba-45cf17e51add.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9920801/bad949a2-5cd7-11e5-9349-e763e8b87333.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9920806/c39dd24c-5cd7-11e5-9681-5131fcb3242a.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9920811/cbf69ed8-5cd7-11e5-9311-42b4859ae530.png)

But it doesn't look too bad with a dark theme either, some screenshots:

![Image](https://cloud.githubusercontent.com/assets/7558360/9921085/5e8a14bc-5cda-11e5-9ece-db3ed5609930.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921087/65bdcf44-5cda-11e5-9c07-909dcd2bf4b4.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921090/6edd9032-5cda-11e5-8e8d-c4dc973472e0.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921096/77121d18-5cda-11e5-8b53-7ecad333f710.png)

One thing I can already conclude from having played around with those colors in Amaze File Manager is, that (IMHO) orange looks better than deep orange as accent color. What do you think?

I'm not really decided between the blue and light blue color though. But I guess light blue would probably fit better with the ConnectBot logo? On the other hand, it might be a bit too much "in your face".

Not sure.

Speaking of decision: After all, maybe it wouldn't be too bad of an idea to let the user chose the primary and accent colors himself, just like in Amaze File Manager?

Regards

**Comment by wp9015362** [comment]
@rhansby :

PS:

Screw what I just said and screw orange :wink:. I've played some more in Amaze File Manager. This time with cyan and blue / light blue and with teal and blue / light blue.

Without orange it looks much better and actually fits to the colors of the ConnectBot logo.

Some screenshots:

![Image](https://cloud.githubusercontent.com/assets/7558360/9921716/fc6309a4-5ce0-11e5-9d84-f66956c53813.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921718/019da244-5ce1-11e5-805d-5cab467893ca.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921722/0852b8f4-5ce1-11e5-8fe3-4da5f3d41f36.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921726/0ed82a38-5ce1-11e5-8daf-d6eefc840ca7.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921728/147222dc-5ce1-11e5-99f1-1b77bb6e360c.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921730/19d38766-5ce1-11e5-87af-5dd33b6a3f95.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921734/1ffa39e6-5ce1-11e5-815c-a16ab9242995.png)

![Image](https://cloud.githubusercontent.com/assets/7558360/9921737/2572b68c-5ce1-11e5-88de-6657be9fec4b.png)

I think it looks much better like that and without orange.

What do you think?

Regards

**Comment by wp9015362** [comment]
@rhansby :

I am just wondering:

Is this still undecided / being worked on?

As far as I am concerned, the accent color really should not be orange nor deep orange (it looks really ugly IMHO and does not fit the ConnectBot logo at all).

As shown on the example screenshots above, I think blue or light blue look way better as an accent color (with cyan as the primary color).

Regards

**Comment by rhansby** [comment]
@wp9015362, we are still actively discussing this topic. I think you can expect updates within the next few days.

**Comment by rhansby** [comment]
Please see #256
