### ISSUE TITLE
Please use floating action button for pubkeys

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#168]
Hello,

I am not a fan of the current UI for adding hosts.

But I have a suggestion to improve it:

The Google Material Design offers a UI element called "Floating Action Button".

You can read about it in the Google Material Design guidelines over there:

https://www.google.com/design/spec/components/buttons-floating-action-button.html

Could you please use a floating action button for adding new hosts?

The button should be placed in the lower right corner of the hosts screen and should make use of the ["ic_add" Material icon](https://www.google.com/design/icons/#ic_add) and when being pressed it should open a new dialog which would offer fields for protocol, hostname (IP), port and username.

Of course the current UI for adding new hosts should then be removed from the hosts screen.

Any chance you could do that? It would make for a much better UI / UX IMHO.

Regards

**Comment by rhansby** [comment]
The floating action button would also greatly benefit the Port forwarding and Pubkey management views. (or any others I haven't noticed)

See screenshots:

![adding awkward](https://cloud.githubusercontent.com/assets/1788374/9914403/9ed7df50-5c66-11e5-9a0c-92b5373d665e.png)

![adding awkward 2](https://cloud.githubusercontent.com/assets/1788374/9914409/a0e73f3e-5c66-11e5-904b-954b02368057.png)

**Comment by khorimoto** [comment]
I'm taking this.

**Comment by wp9015362** [comment]
>  @khorimoto wrote:
>
> I'm taking this.

Thank you.

I came across the following article today:

http://www.androidauthority.com/android-design-support-library-overview-636694/

Maybe it can be helpful.

Regards

**Comment by jklein24** [comment]
Hostlist has FAB from https://github.com/connectbot/connectbot/pull/219/files. @khorimoto or @rhansby, do either of you want to add it to pubkeys and port forwards?

**Comment by khorimoto** [comment]
Yeah, I can do it.

**Comment by wp9015362** [comment]
@bengolds :

I see that you have added a "MVP" label to some issues.

May I ask what "MVP" stands for?

Just curious.

Regards

**Comment by bengolds** [comment]
We are making a batch of improvements for Android productivity tablets (N9 with folio keyboard), and this is a sort of "Minimum Viable Product" for SSH productivity on those devices.

**Comment by jklein24** [comment]
https://github.com/connectbot/connectbot/pull/268 landed for Port Forwarding. Just need pubkeys :-)
