### ISSUE TITLE
Toolbar only says "ConnectBot" when being in the settings and when being on the edit host screen

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#170]
Hello,

when being in the settings, the toolbar only says "ConnectBot".

But it should say "Settings".

Could you please fix it?

Regards

**Comment by wp9015362** [comment]
PS:

The same is also true for when being on the edit host screen.

When being on the edit host screen, the toolbar only says "ConnectBot".

But it should say "Edit host".

Regards

**Comment by kruton** [comment]
Already done in 3ee07166ee1aa584686b631341cb5dabc32359e5.
