### ISSUE TITLE
Please remove "ConnectBot: " from the toolbar and simply make it say on which screen you are

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#171]
Hello,

in the toolbar, ConnectBot says on which screen you are ([except for when being in the settings and on the edit host screen](https://github.com/connectbot/connectbot/issues/170)), i.e.:

- ConnectBot: Hosts
- ConnectBot: Pubkeys
- ConnectBot: Colors
- ConnectBot: Help
- ConnectBot: Help - Hints
- ConnectBot: Help - PhysicalKeyboard
- ConnectBot: Help - ScreenGestures
- ConnectBot: Help - VirtualKeyboard

This is good.

But the "ConnectBot: " part in front of it is completely unnecessary IMHO.

I have never seen any other app doing it like this.

Could you please remove the "ConnectBot: " part and simply make the toolbar say on which screen you are (i.e. change "ConnectBot: Hosts" to simply "Hosts" and so on)?

It would be much appreciated.

Regards

**Comment by kruton** [comment]
Already done in 3ee07166ee1aa584686b631341cb5dabc32359e5.
