### ISSUE TITLE
Toolbar does not show hostname

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#172]
Hello,

in the terminal, the toolbar does not show the hostname, it only shows the ConnectBot logo and says "ConnectBot".

You can see what I mean on the following screenshot:

![Image](https://cloud.githubusercontent.com/assets/7558360/9573724/ec1149f4-4fbf-11e5-95c4-e860839cac38.png)

Could you please remove the logo and simply make it say the hostname instead (i.e. replacing "ConnectBot" with the actual hostname)?

It would be much appreciated.

Regards

**Comment by kruton** [comment]
I think this was already fixed by 6ef56cfec3ce625d1a16ca960417dac19ebca45c.
