### ISSUE TITLE
Font in toolbar is not bold

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#174]
Hello,

in any other app that I know of, the toolbar is using bold font.

But ConnectBot is not using a bold font in it's toolbar.

Could you please fix it and use a bold font in the toolbar?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
PS:

The Google Material Design guidelines appear to say that it should be "Medium 20sp", see:

https://www.google.com/design/spec/style/typography.html

Regards

**Comment by rhansby** [comment]
@wp9015362, can you please clarify which element of the app you're referring to as the toolbar? (a screenshot would be preferred)

**Comment by wp9015362** [comment]
@rhansby :

Yes, of course, here is a screenshot of ConnectBot 1.8.6:

![Image](https://cloud.githubusercontent.com/assets/7558360/9947373/ec4729e2-5d99-11e5-83c0-2b0a0785b298.png)

As you can see, I have highlighted the area which shows the toolbar (sometimes also being referred to as appbar) in a red rectangle. I am not really sure if there is any difference between the term "toolbar" and the term "appbar". Both terms always seem to refer to the same element. Even the Google Material Design Guidelines seem to mix up these two terms when referring to this element. So "toolbar" and "appbar" probably means the same (at least as far as I can tell).

And, as you can see, the font that is being used for the text inside the toolbar, which says "ConnectBot" in this case, is not bold.

However, in all other Material Design apps that I know, like [Amaze File Manager](https://github.com/arpitkh96/AmazeFileManager) for example, the font in the toolbar is bold, as shown in the following screenshot of Amaze File Manager:

![Image](https://cloud.githubusercontent.com/assets/7558360/9947438/678a36b2-5d9a-11e5-96b1-ce6fc362d129.png)

The Google Material Design Guidelines say:

> https://www.google.com/design/spec/style/typography.html#typography-styles
> 
> [...]  Across form factors, text that appears in the app bar should use the Title style, Medium 20sp. [...]

Regards

**Comment by wp9015362** [comment]
PS:

@rhansby :

Since I am still on version 1.8.6 from the Google Play Store, could it be possible that this issue was already fixed with:

https://github.com/connectbot/connectbot/commit/3ee07166ee1aa584686b631341cb5dabc32359e5

?

Because, when I am looking at the screenshots that you and @kruton have posted in https://github.com/connectbot/connectbot/pull/205 and in https://github.com/connectbot/connectbot/issues/167, then the font actually seems to be bold now?

You are probably running a self-compiled version fresh from git which contains https://github.com/connectbot/connectbot/commit/3ee07166ee1aa584686b631341cb5dabc32359e5?

Whereas I am still running the current (i.e. old in comparison) version from the Google Play Store which does not (yet) include https://github.com/connectbot/connectbot/commit/3ee07166ee1aa584686b631341cb5dabc32359e5.

So, maybe https://github.com/connectbot/connectbot/commit/3ee07166ee1aa584686b631341cb5dabc32359e5 already fixed this, but not sure.

Regards

**Comment by rhansby** [comment]
You're correct, the screenshots that I have been posting are self-compiled, and ahead of the Play Store release version.

After reverting through various git commits, it does look like #197 solved this issue.

**Comment by rhansby** [comment]
@kruton please close this issue.
