### ISSUE TITLE
Please add "Quit" button to main menu

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#176]
Hello,

ConnectBot has a main menu which offers the following options/buttons:

- Sort by color/name
- Manage Pubkeys
- Colors
- Settings
- Help

Could you please add another button/option called "Quit" or "Exit" to the main menu which disconnects from all hosts and closes ConnectBot?

It would be much appreciated.

Regards

**Comment by kruton** [comment]
I think "Disconnect all" would be useful, but not a "Quit" button. That goes against Android UX guidelines.
