### ISSUE TITLE
Adjusting Font Size

### ISSUE THREAD

**Issue by MikeRivers** [connectbot/connectbot#179]
I had an older version that allowed me to change the font size on the phone screen, though I can't say as I remember how I did it. The current version is way too small. When I try to resize using the menu, it always goes back to 80x25.

I saw something, probably in the Help menu, for using the volume control to change size, but that doesn't do anything. 

Phone is a ZTE 740, Android 4.1.2. What am I missing?

**Comment by kruton** [comment]
Are you using the volume keys while in the console activity (e.g., SSH into the host, etc) and without the menu activated?

**Comment by MikeRivers** [comment]
On 9/14/2015 10:08 AM, Kenny Root wrote:
> Are you using the volume keys while in the console activity (e.g., SSH
> into the host, etc) and without the menu activated?

I don't remember. I doubt it. But I eventually found a setting for the 
host that specified the font size and that did the trick. I use the 
program on only one host and for text only, so for me the simplest 
solution is best.


-- 
For a good time call http://mikeriversaudio.wordpress.com
