### ISSUE TITLE
Local shell is not closed when disconnecting

### ISSUE THREAD

**Issue by aykevl** [connectbot/connectbot#200]
After the shell is closed via the 'Disconnect' menu item, the process of that shell is not closed or killed. In the screenshots below, I opened a shell, ran the command, disconnected, opened the shell again, and ran the same command. You see in the second screenshot that the 'sh' process is still alive, which is unexpected.

This is also a problem when using 'su' in CyanogenMod: the '#' mark stays in the statusbar after closing the shell, and is only removed when closing ConnectBot in the app overview.

![screenshot_2015-09-12-11-16-21](https://cloud.githubusercontent.com/assets/729697/9830874/da18c572-593f-11e5-80a1-aa29f54dc336.png) ![screenshot_2015-09-12-11-16-55](https://cloud.githubusercontent.com/assets/729697/9830875/e07d17ec-593f-11e5-91d0-49505492de09.png)

**Comment by kruton** [comment]
Thanks for the report.
