### ISSUE TITLE
Host list connection indicator does not use colors from Google Material Design Color Palette

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#202]
Hello,

@khorimoto recently redesigned the host list via:

https://github.com/connectbot/connectbot/pull/185

As already mentioned in:

https://github.com/connectbot/connectbot/issues/167

I noticed that the connection indicator (the green/red circle that shows if a host is connected or disconnected) does not use colors from the [Google Material Design Color Palette](https://www.google.com/design/spec/style/color.html#color-color-palette).

Maybe it would make sense to make that indicator use a green color (connected) and red color (disconnected) which is part of the [Google Material Design Color Palette](https://www.google.com/design/spec/style/color.html#color-color-palette)?

Regards

**Comment by rhansby** [comment]
Taking this.

**Comment by wp9015362** [comment]
This issue could be solved by replacing the connection status indicators on the host list with Material icons, as requested in:

https://github.com/connectbot/connectbot/issues/217

Regards

**Comment by rhansby** [comment]
@kruton or @jklein24 can you please close this issue as it has been closed by #233
