### ISSUE TITLE
Pubkey generation view uses uncolored primary action button

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#208]
The primary action button, "Generate", is uncolored. This likely goes against Material Design guidelines and is visually confusing.

Screenshot attached:
![pubkey uncolored button](https://cloud.githubusercontent.com/assets/1788374/9913990/9444b2ea-5c64-11e5-9fbd-c52e03dc5f1a.png)

**Comment by wp9015362** [comment]
@rhansby :

Now that you mention it:

The pubkey generation view also has two checkboxes. They should also be changed to switches to adhere to the Google Material Design Guidelines:

https://github.com/connectbot/connectbot/issues/169
https://github.com/connectbot/connectbot/issues/205

Regards
