### ISSUE TITLE
Connection status indicators on host list could be replaced with Material icons

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#217]
Hello,

similar to what @rhansby suggested in https://github.com/connectbot/connectbot/issues/207 and fixed with https://github.com/connectbot/connectbot/pull/216, the connection status indicators on the host list (the green and red circles next to the hostnames) could also be replaced with Material icons.

This would then also fix https://github.com/connectbot/connectbot/issues/202.

For the connected status, the following Material icons could be used:
[ic_phonelink](https://www.google.com/design/icons/#ic_phonelink)
or:
[ic_cast_connected](https://www.google.com/design/icons/#ic_cast_connected)
or:
[ic_wifi](https://www.google.com/design/icons/#ic_wifi)

For the disconnected status, the following Material icons could be used:
[ic_phonelink_off](https://www.google.com/design/icons/#ic_phonelink_off)
or:
[ic_cast](https://www.google.com/design/icons/#ic_cast)
or:
[ic_signal_wifi_off](https://www.google.com/design/icons/#ic_signal_wifi_off)

Regards

**Comment by khorimoto** [comment]
I agree material icons would be nice, but I'm not sure the ones provided are actually good to use since they already have other implications (e.g., Chromecast, Wi-Fi, etc). Any other icon ideas?

**Comment by rhansby** [comment]
Closely related to #202

**Comment by wp9015362** [comment]
@khorimoto :

Some more ideas:

Connected status:

[ic_leak_add](https://www.google.com/design/icons/#ic_leak_add)
or:
[ic_play_circle_filled](https://www.google.com/design/icons/#ic_play_circle_filled)
or:
[ic_play_circle_outline](https://www.google.com/design/icons/#ic_play_circle_outline)
or:
[ic_play_arrow](https://www.google.com/design/icons/#ic_play_arrow)

Disconnected status:

[ic_leak_remove](https://www.google.com/design/icons/#ic_leak_remove)
or:
[ic_pause_circle_filled](https://www.google.com/design/icons/#ic_pause_circle_filled)
or:
[ic_pause_circle_outline](https://www.google.com/design/icons/#ic_pause_circle_outline)
or:
[ic_pause](https://www.google.com/design/icons/#ic_pause)
or:
[ic_stop](https://www.google.com/design/icons/#ic_stop)

Regards

**Comment by khorimoto** [comment]
What about this:

Green [ic_check_circle] (https://www.google.com/design/icons/#ic_check_circle) for connected.

Red [ic_remove_circle] (https://www.google.com/design/icons/#ic_remove_circle) for disconnected.

**Comment by wp9015362** [comment]
@khorimoto :

No offence, but, personally, I do not like those icons for this purpose.

I also think colors should be avoided for the Material icons.

Actually, there is a specific Google Material Icon Guide, see:

https://google.github.io/material-design-icons/

And regarding colors it says:

> https://google.github.io/material-design-icons/
> 
> Coloring
> 
> [...] In accordance with [material design icon guidelines](https://www.google.com/design/spec/style/icons.html#icons-system-icons), for active icons we recommend using either black at 54% opacity or white at 100% opacity when displaying these on light or dark backgrounds, respectively. If an icon is disabled or inactive, using black at 26% or white at 30% for light and dark backgrounds, respectively. [...]

Here is the part from the Google Material Design System Icons Guideline which the Google Material Icon Guide is referring to:

> https://www.google.com/design/spec/style/icons.html#icons-system-icons
> 
> Color
> 
> [...] The standard opacity for an active icon on a light background is 54% (#000000). An inactive icon, which is lower in the visual hierarchy, should have an opacity of 26% (#000000).
> 
> The standard opacity for an active icon on a dark background is 100% (#FFFFFF). An inactive icon, which is lower in the visual hierarchy, should have an opacity of 30% (#FFFFFF). [...]

So, as far as I can tell from reading this, colors other than black or white are not recommended for Material icons.

I also haven't seen any other app that uses Material icons in colors other than black and white.

So, I'd say ConnectBot shouldn't do that either.

After having read those guidelines mentioned above, I think a much better idea would be to use just one icon instead of two and make this one icon display as active for the connected status and inactive for the disconnected status (by adjusting the opacity as mentioned in the guidelines above).

I guess from all the Material icons which are currently available, the ["ic_leak_add" Material icon](https://www.google.com/design/icons/#ic_leak_add) would probably be the best for this.

How about you?

Regards

**Comment by khorimoto** [comment]
Ah - thanks for pointing out the rules about colors.

Hmm, I still don't think the ic_leak_add icon looks good. I wonder if we could create our own icons.

**Comment by wp9015362** [comment]
> @khorimoto wrote:
> 
> Hmm, I still don't think the ic_leak_add icon looks good.

And what do you think about the idea to use just one icon and display it as either active (when connected) or inactive (when disconnected) by adjusting the opacity?

> @khorimoto wrote:
> 
> I wonder if we could create our own icons.

A quick Google search came up with the following website, which apparently has some additional "Material" icons "from the community", see:

https://materialdesignicons.com/

It also has a link to GitHub in the upper right corner which links to the following repository:

https://github.com/Templarian/MaterialDesign

Maybe it has an icon that you like better?

Speaking about what you like:

If you would create your own icon, what would it look like :wink:?

Regards

**Comment by wp9015362** [comment]
@khorimoto :

There is an open feature request in the repository mentioned above which would very probably be related to this issue, see:

https://github.com/Templarian/MaterialDesign/issues/369

I think the icons in https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-139826493 already look very promising for the ConnectBot host list connection status indicator. How about you?

Regards

**Comment by wp9015362** [comment]
PS:

Another related icon request:

https://github.com/Templarian/MaterialDesign/issues/124

Regards

**Comment by wp9015362** [comment]
And one more:

https://github.com/Templarian/MaterialDesign/issues/427

:wink:

But I guess the most promising one would still be:

https://github.com/Templarian/MaterialDesign/issues/369

Regards

**Comment by wp9015362** [comment]
@khorimoto :

In https://github.com/Templarian/MaterialDesign/issues/369 I have asked @CoDEmanX for a suggestion.

He kindly came up with this:

> Connected:
> ![lan-laptops4](https://cloud.githubusercontent.com/assets/1309249/9834289/9d484954-59b4-11e5-8da3-c35a6bf63736.png)
> Disconnected:
> ![lan-laptops3-disconnected](https://cloud.githubusercontent.com/assets/1309249/9962780/d60bfeee-5e27-11e5-8cc1-675fc6b5cf6a.png)

What do you think?

Regards

**Comment by khorimoto** [comment]
Nice - that one looks good to me. @kruton, @alescdb, @rhansby, @jklein24?

**Comment by kruton** [comment]
Why did the monitors get bigger when it disconnected? :) There are three states, though: not yet connected, connected, disconnected. I think I originally intended for disconnected to be an indicator that maybe you were connected but a network event caused the connection to be dropped.

**Comment by rhansby** [comment]
what about:

not yet connected: https://www.google.com/design/icons/#ic_not_interested
![ic_not_interested_black_36dp](https://cloud.githubusercontent.com/assets/1788374/9966139/dade1e8a-5def-11e5-9615-239004684dfa.png)

connected: https://www.google.com/design/icons/#ic_check_circle


disconnected: https://www.google.com/design/icons/#ic_error

**Comment by khorimoto** [comment]
I like connected, but it might be hard to differentiate between not yet
connected and disconnected. But, then again, it's already a little hard to
differentiate between the current icons too :)

**Comment by wp9015362** [comment]
@rhansby :

@khorimoto alreasy suggested that in https://github.com/connectbot/connectbot/issues/217#issuecomment-141296436. But, as already mentioned in https://github.com/connectbot/connectbot/issues/217#issuecomment-141303294, I personally do not like those icons for this purpose.

> @kruton wrote:
> 
> Why did the monitors get bigger when it disconnected? :) There are three states, though: not yet connected, connected, disconnected. I think I originally intended for disconnected to be an indicator that maybe you were connected but a network event caused the connection to be dropped.

Sorry, my mistake, unfortunately I posted the "lan-laptops4" icon at first for the connected icon, even though it should have been the "lan-laptops3" icon. The "lan-laptops3" icon has the same size as the disconnected icon.

Regarding the "not yet connected" (i.e. pending connection) icon:

@CoDEmanX also posted an icon with dotted lines ("lan-laptops2").

So how about this:

> Not yet connected:
> ![lan-laptops2](https://cloud.githubusercontent.com/assets/1309249/9834288/9d481d9e-59b4-11e5-8f9a-394556f64825.png)
> Connected:
> ![lan-laptops3](https://cloud.githubusercontent.com/assets/1309249/9834291/9d49e962-59b4-11e5-9bda-98cd651a123d.png)
> Disconnected:
> ![lan-laptops3-disconnected](https://cloud.githubusercontent.com/assets/1309249/9962780/d60bfeee-5e27-11e5-8cc1-675fc6b5cf6a.png)

?

Anyway, I have asked @CoDEmanX for yet another suggestion regarding the "not yet connected" icon and I also came up with the idea to use a small clockface in place where the line/cross is in the connected/disconnected icon, see:

https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-141514491

Besides, I'd say it would make more sense if you would reply in the respective thread (https://github.com/Templarian/MaterialDesign/issues/369) since discussing the same issue among two threads becomes messy.

PS:

For the record, this is the post where he showed the "lan-laptops2" and "lan-laptops3" icons:

https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-139826493

And this is the post where he showed the "lan-laptops3-disconnected" icon:

https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-141478503

As you can see, he also posted a link to the the SVG sources.

@Templarian just said that he will include them in the collection tonight, see https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-141509277.

Regards

**Comment by wp9015362** [comment]
> @khorimoto wrote:
> 
> I like connected, but it might be hard to differentiate between not yet connected and disconnected.

Well, I really do not like the check circle icon for the connected status, but here is a possible solution for the not yet connected and disconnected discernibility issue and also a rather nice alternative for the connected status, see:

Not yet connected ([ic_access_time](https://www.google.com/design/icons/#ic_access_time)):
![ic_access_time](https://raw.githubusercontent.com/google/material-design-icons/master/device/drawable-xxxhdpi/ic_access_time_black_24dp.png)

Connected ([ic_swap_vertical_circle](https://www.google.com/design/icons/#ic_swap_vertical_circle)):
![ic_swap_vertical_circle](https://raw.githubusercontent.com/google/material-design-icons/master/action/drawable-xxxhdpi/ic_swap_vertical_circle_black_24dp.png)

Disconnected ([ic_highlight_off](https://www.google.com/design/icons/#ic_highlight_off)):
![ic_highlight_off](https://raw.githubusercontent.com/google/material-design-icons/master/action/drawable-xxxhdpi/ic_highlight_off_black_24dp.png)

How do you like that @khorimoto / @rhansby ?

Regards

**Comment by wp9015362** [comment]
@khorimoto :

He has posted an update, see:

https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-141533645

You like it?

Regards

**Comment by wp9015362** [comment]
@khorimoto :

The icons have now been added to the collection.

Here are two variants, which I think should be used for ConnectBot.

Either this variant:

Pending:
[timer-sand](https://materialdesignicons.com/icon/timer-sand)
![timer-sand](https://cloud.githubusercontent.com/assets/7558360/10022174/c3d8d914-614b-11e5-8146-4d1a8d8abf86.png)
Connected:
[ethernet-cable](https://materialdesignicons.com/icon/ethernet-cable)
![ethernet-cable](https://cloud.githubusercontent.com/assets/7558360/10021982/e20ed7f4-614a-11e5-9ec7-492d410f4d3b.png)
Disconnected:
[ethernet-cable-off](https://materialdesignicons.com/icon/ethernet-cable-off)
![ethernet-cable-off](https://cloud.githubusercontent.com/assets/7558360/10022040/2901ade4-614b-11e5-91d7-4df9417bfa54.png)

Or alternatively this variant:

Pending:
[lan-pending](https://materialdesignicons.com/icon/lan-pending)
![lan-pending](https://cloud.githubusercontent.com/assets/7558360/10021869/626c7f56-614a-11e5-9e41-17b07ce8ce7c.png)
Connected:
[lan-connect](https://materialdesignicons.com/icon/lan-connect)
![lan-connect](https://cloud.githubusercontent.com/assets/7558360/10021853/50a52d5e-614a-11e5-8d12-98210971605b.png)
Disconnected:
[lan-disconnect](https://materialdesignicons.com/icon/lan-disconnect)
![lan-disconnect](https://cloud.githubusercontent.com/assets/7558360/10021906/83003bd6-614a-11e5-975d-06b8ee9e71e1.png)

Regards

**Comment by bengolds** [comment]
rhansby, I'd prefer your choices here. If "disconnected" signals a problem, the "error" exclamation mark is a good match for it. The check circle feels like a great fit here as well.

Also, colorizing the icons is totally acceptable; they even have instructions for [doing so here](https://google.github.io/material-design-icons/). The existing color scheme is a good fit here and communicates well, which is the main point.

**Comment by rhansby** [comment]
@bengolds thanks for the guidance. 

I've created a PR at #233 and I'd appreciate if you all looked over it.
