### ISSUE TITLE
ActionBar is missing in subviews of main view

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#224]
I'm not sure what caused this regression. Perhaps switching to AppCompatActivity? @khorimoto?

See Settings screenshot as of commits 3de02e7 and f8a77f6: 
![actionbar f8a77f6](https://cloud.githubusercontent.com/assets/1788374/9967992/d56d3caa-5dfa-11e5-85c1-c3d36ceedded.png)

And then the same view as of master right now:
![actionbar master](https://cloud.githubusercontent.com/assets/1788374/9968035/0ffd4b44-5dfb-11e5-8ae6-eddd47cc93f4.png)

**Comment by khorimoto** [comment]
I don't think this has to do with AppCompatActivity because that only
changed the HostListActivity, not the PreferencesActivity. And on
HostListActivity, there IS an ActionBar.

**Comment by rhansby** [comment]
There is still an ActionBar on the main view, but all other subviews are missing ActionBars where they previously had them:

master:
![pubkeymaster](https://cloud.githubusercontent.com/assets/1788374/9968305/922ef260-5dfc-11e5-9c4b-61e3468403d9.png)

f8a77f6:
![pubkey f8a77f6](https://cloud.githubusercontent.com/assets/1788374/9968318/9ca941be-5dfc-11e5-8f91-3ffa1e85aeb0.png)

**Comment by rhansby** [comment]
I suspect HostListActivity becauseI believe it is the parent of all these subviews (not sure about that though)

**Comment by wp9015362** [comment]
@kruton :

In https://github.com/connectbot/connectbot/issues/173 you said that the missing back button issue would have been fixed by https://github.com/connectbot/connectbot/issues/173.

But on the screenshots posted by @rhansby the back button is still missing.

Are you sure this was fixed with https://github.com/connectbot/connectbot/pull/197?

Regards

**Comment by rhansby** [comment]
We found the way to fix this issue, and I'm working on it now. The fix I'm working on will resolve this issue and #173. :)

Here's a screenshot of the fix in action: 
![fix](https://cloud.githubusercontent.com/assets/1788374/9973269/9bd804be-5e24-11e5-87ba-91585d6cc418.png)

It will take a bit of time for me to polish but for now you can see it in progress at https://github.com/rhansby/connectbot/commits/convert-activities-to-appcompat
