### ISSUE TITLE
Intempestive closed connection reopening

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#227]
1 - Start ConnectBot
2 - Open a connection
3 - Return to host list
4 - Open a second connection (local)
5 - Type "exit" and answer "Yes" if asked (second connection is now closed)
6 - Power off device
7 - Power on device
8 - Second connection is reopening.

It also happens when you switch to another task and come back (onResume() ?)

**Comment by alescdb** [comment]
Seems resolved by #307

**Comment by jklein24** [comment]
Nice! I wonder if it was just moving `bound = null` to the top of the onServiceDisconnected function.
