### ISSUE TITLE
Connection closed detection

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#228]
This may be related to issue #227

1 - Start ConnectBot
2 - Open a connection
3 - Power off device
4 - Power on device
5 - Type "exit" to close the connection
6 - Console say "Connection closed" but no button yes/no to close the activity (need to menu -> Disconnect)

**Comment by alescdb** [comment]
Since this has not been tagged as "Bug", I'm assuming I'm the only one to have this behaviour ?

I tried on a fresh install of CB (git-v1.8.6-348-g69739ad) and it's still happening for me :-/

**Comment by rhansby** [comment]
Has this issue been solved in the same way that #227 has been solved?

**Comment by alescdb** [comment]
@rhansby Nope still stuck on the console with a closed connection (by shell command) after switching app or screen off.
