### ISSUE TITLE
Empty HostList feels awkward

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#231]
With the addition of the FAB in #219, a "quick-connect box" is no longer displayed at the bottom of the view, making the language of the below screenshot incorrect: 

However, I'm not sure if we should simply update the language to "use the button below..." as that seems like bad UX. We could remove the blurb altogether, but then it isn't at all clear that we are on the HostList view.

Thoughts?

![hosts discus](https://cloud.githubusercontent.com/assets/1788374/10032101/d8ee4b7e-6135-11e5-916b-6e7724351b11.png)

**Comment by jklein24** [comment]
cc @bengolds.

Changing the messaging would be fine IMO. I agree that removing the blurb altogether wouldn't look right. Maybe just "No hosts created yet" or something along those lines.

**Comment by bengolds** [comment]
Agreed; change the blurb. In the best of all worlds, a cute illustration would fit nicely. That said, don't worry about it.

**Comment by rhansby** [comment]
Taking this issue.
