### ISSUE TITLE
Floating action button is hidding connection status

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#241]
![screenshot_20150923-204501](https://cloud.githubusercontent.com/assets/5646825/10054968/37f256b6-6234-11e5-9492-57545586582f.png)

**Comment by rhansby** [comment]
This seems to be a common issue in other projects: http://graphicdesign.stackexchange.com/questions/50412/how-do-i-keep-my-floating-action-button-from-blocking-other-components

We could either:
* move the button (e.g. the bottom center or upper right)
* hide the button on scroll (I don't think that solves this issue, however)
* add padding to the bottom of the list (apparently Gmail uses this solution)

**Comment by alescdb** [comment]
Or move the status icon to the left ?
Hidding part of the name is less anoying than connection status.

**Comment by jklein24** [comment]
Let's go with option 3 here.

**Comment by kruton** [comment]
It also looks like the FAB has no shadow so it doesn't appear to be "layered" on top of the list.
