### ISSUE TITLE
GeneratePubkey view crashes on older APIs

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#249]
This seems to be caused by this call:
https://github.com/connectbot/connectbot/commit/5b8cc2d070eb3e22c13ecd586b589d68c800f5d6#diff-e03d035f94681f9f049ba487a7ea693bR229

**Comment by kruton** [comment]
Can you try to add an androidTest for going to the generate key screen?
Then the device tests will catch it at least.
