### ISSUE TITLE
IME keyboard is not being opened when tapping on the terminal

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#263]
Hello,

when tapping on the terminal, the virtual keyboard (the one with the ESC, CTRL, TAB, UP, DOWN, LEFT, RIGHT buttons) is being opened.

To open the actual IME keyboard, you need to press the keyboard button on the virtual keyboard.

So you have to tap twice to open the IME keyboard.

IMHO, instead of just opening the virtual keyboard when tapping on the terminal, the IME keyboard should open as well.

Could you do that?

Regards

**Comment by alescdb** [comment]
I'm not sure this is a good idea. The keyboard not showing on click is actually useful if you just need to access the copy/paste/menu the Actionbar/Toolbar is in autohide mode.

**Comment by wp9015362** [comment]
> @alescdb wrote:
> 
> I'm not sure this is a good idea. The keyboard not showing on click is actually useful if you just need to access the copy/paste/menu the Actionbar/Toolbar is in autohide mode.

This is not an issue, because long tapping the terminal actually doesn't open the virtual keyboard either, it only opens the copy/paste-menu :smiley:. Just try it :wink:.

Currently it works like this:

Long tapping the terminal (pressing and holding) = opening copy/paste-menu without opening any keyboard
Short tappping the terminal (just pressing biefly) = opening virtual keyboard

So, the only thing my request would change would be that the IME keyboard would also open when short tapping the terminal.

Long tapping the terminal would still get you to the copy/paste menu without opening any keyboard :wink:.

Regards

**Comment by alescdb** [comment]
Long tapping open the context menu "Paste", but does not show the "Copy" or the Toolbar/Actionbar if you have the options "Autohide Toolbar" in the setup.

**Comment by wp9015362** [comment]
> @alescdb wrote:
> 
> Long tapping open the context menu "Paste", but does not show the "Copy" or the Toolbar/Actionbar if you have the options "Autohide Toolbar" in the setup.

Yep, I just realized that myself. I have opened a issue for it, see:

https://github.com/connectbot/connectbot/issues/265

Regards

**Comment by rhansby** [comment]
> So you have to tap twice to open the IME keyboard.

> IMHO, instead of just opening the virtual keyboard when tapping on the terminal, the IME keyboard > should open as well.

Do others agree with this? @kruton @jklein24 (I personally do not)

If not, this issue should be closed.

**Comment by kruton** [comment]
No, this would interact too badly with copy/paste or create another state which seems needless.
