### ISSUE TITLE
Font size in Manage Pubkeys list and Port forwards list is way too big

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#264]
Hello,

the font size in the Manage Pubkeys list is way too big.

It should follow the specs from https://www.google.com/design/spec/components/lists.html.

It's the same issue as it was with the host list in https://github.com/connectbot/connectbot/issues/175.

@khorimoto or @rhansby :

Any chance you could fix that as well, just as it was fixed in https://github.com/connectbot/connectbot/pull/185 for the host list?

PS: It would be nice if you could also do https://github.com/connectbot/connectbot/issues/253 while being at it, since the icons in the Manage Pubkeys list are also affected by https://github.com/connectbot/connectbot/issues/253 .

Regards

**Comment by khorimoto** [comment]
Yep, I can take this after I'm done with some other work.

**Comment by wp9015362** [comment]
@khorimoto :

Now that I know [how to access the port forwards activity](https://github.com/connectbot/connectbot/pull/268#issuecomment-148131518) (thanks :wink:), I can report that the port forwards lists is also affected by this issue.

Regards

**Comment by rhansby** [comment]
Taking this, and also aligning pubkey icons on left as per #253
