### ISSUE TITLE
Long tapping the terminal only offers Paste, but should offer Copy and Paste

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#265]
Hello,

when long tapping (pressing and holding) on the terminal, the user is only being offered with "Copy". Once the user has copied something, long pressing on the terminal only offers "Paste".

But it should offer "Copy" ***and*** "Paste", otherwise it would only be possible to paste the previously copied text and would no longer be possible to copy anything else (at least not without having to resort to the toolbar menu).

So, could you please fix this and make long pressing on the terminal also offer "Copy" ***and*** "Paste" after something has been copied?

Regards

**Comment by jklein24** [comment]
> when long tapping (pressing and holding) on the terminal, the user is only being offered with "Copy". Once the user has copied something, long pressing on the terminal only offers "Paste".

I'm pretty sure it *only* ever shows paste at the moment and never copy. For now, the user can use the action bar copy and paste buttons, but we're also looking into reworking the copy/paste flow altogether so  I'd rather not mess with this until then.

**Comment by wp9015362** [comment]
> @jklein24 wrote:
> 
> I'm pretty sure it only ever shows paste at the moment and never copy. For now, the user can use the action bar copy and paste buttons,

Yes, sorry, you are correct, it actually only ever offers paste.

> @jklein24 wrote:
> 
> For now, the user can use the action bar copy and paste buttons

Yeah, but in https://github.com/connectbot/connectbot/issues/263 @alescdb mentioned that some users might have the toolbar hidden, which actually lead me to open this issue.

> @jklein24 wrote:
> 
>  but we're also looking into reworking the copy/paste flow altogether so I'd rather not mess with this until then.

May I ask what that will look like?

And is there some kind of to-do list for ConnectBot which could be made publicly available maybe?

Regards

**Comment by wp9015362** [comment]
PS:

> @jklein24 wrote:
> 
>  but we're also looking into reworking the copy/paste flow altogether so I'd rather not mess with this until then.

Ah, I just saw that you are probably referring to this (?):

https://github.com/connectbot/connectbot/pull/129

Regards

**Comment by jklein24** [comment]
Yep, exactly :-). #129 is roughly the goal.

**Comment by rhansby** [comment]
This issue should be closed, it was fixed by #277
