### ISSUE TITLE
ConnectBot still appears as "Serveurs" (Locale.FRENCH) in launcher applications (git-v1.8.6-275-gd88325b)

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#269]
It seems #245 did not fix this for my Nexus 9 latest 5.1.1 with Google Launcher (1.1.1.1706998).
It's ok on my Nexus 5 (Marshmallow preview 3).
At first I thougth it was a cache problem somewhere but clearing Google Launcher cache and uninstall/install ConnectBot did not resolved it.

**Comment by alescdb** [comment]
Also (my opinion), when starting an application it feels natural to have the name of that application in the main Activity,  so when we open recent apps we search for "ConnectBot" and not "Hosts".
Maybe ActionBar.setSubtitle() can be used instead ?

http://developer.android.com/reference/android/app/ActionBar.html#setSubtitle(java.lang.CharSequence

**Comment by wp9015362** [comment]
> @alescdb wrote:
> 
> Also (my opinion), when starting an application it feels natural to have the name of that application in the main Activity

I get your point, but it's not too uncommon for apps not to have the app name in the App Bar of the main activity (main/home screen).

Let's take some Google apps for example:

The [Gmail app](https://play.google.com/store/apps/details?id=com.google.android.gm) does ***not*** say "Gmail" in the App Bar of it's main activity. Instead the App Bar shows which email label/folder is being shown at the moment.

The [YouTube app](https://play.google.com/store/apps/details?id=com.google.android.youtube) also does ***not*** say "YouTube" in the App Bar of it's main activity. Instead the App Bar says "Home" or "Subscritions" or "Account" (depending on which tab of the main activity you are).

On the other hand though, the [Hangouts app](https://play.google.com/store/apps/details?id=com.google.android.talk) and the [Messenger app](https://play.google.com/store/apps/details?id=com.google.android.apps.messaging) for example do say "Hangouts" and "Messenger" in the App Bar of their main activity.

So, some apps don't show the app name in the App Bar of their main activity and some do.

> @alescdb wrote:
> 
>  so when we open recent apps we search for "ConnectBot" and not "Hosts".

Well, even though the App Bar in the main activity of the [Gmail app](https://play.google.com/store/apps/details?id=com.google.android.gm) and the [YouTube app](https://play.google.com/store/apps/details?id=com.google.android.youtube) do ***not*** say "Gmail" and "YouTube", the recent apps screen of Android still ***does*** show "Gmail" and "Youtube", so there must be a way to make ConnectBot say "Hosts" in the App Bar of the main activity but still say "ConnectBot" in the recent apps of Android.

Regards

**Comment by wp9015362** [comment]
PS:

For the record, I have looked up what the Google Material Design Guidelines say about the App Bar, they say:

> https://www.google.com/design/spec/layout/structure.html#structure-app-bar
> 
> [...] The app bar, formerly known as the action bar in Android, is a special kind of toolbar that’s used for branding, navigation, search, and actions. [...] The title in the app bar reflects the current page. It can be an app title, page title, or a page filter. [...]

Regards

**Comment by kruton** [comment]
I think we'll have to do `setTitle(...)` in `HostListActivity` to support older devices as well.

**Comment by rhansby** [comment]
I didn't see this issue at the time, but #278 fixed this. The change uses `setTitle` as @kruton suggests.

**Comment by kruton** [comment]
That's what I thought happened.
