### ISSUE TITLE
Unable to show the ActionBar (when set to auto hide)

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#285]
Since the very nice #277 when actionbar (Toolbar) is set to auto hide in settings, touching the screen does not show the action bar.

**Comment by alescdb** [comment]
Also, it's almost impossible (but sometime possible) to hit the paste icon in action bar.

**Comment by rhansby** [comment]
I've fixed the issue with the ActionBar hiding/showing in #291.

@alescdb, I haven't been able to replicate the paste icon issue. Could you tell me under what conditions the paste button does/doesn't work?
