### ISSUE TITLE
Can't hit Paste (SSH only)

### ISSUE THREAD

**Issue by alescdb** [connectbot/connectbot#295]
OK I think I nailed it.
It only happens with SSH host. When connecting and after it is impossible to hit paste, if I select "Force size" in the menu, it then enable the Paste icon.

Nexus 5 with 6.0.

**Comment by rhansby** [comment]
Is this still occurring after #293?

**Comment by alescdb** [comment]
Yes it is. Only on SSH hosts. Maybe it's disabled somewhere programmatically ?

**Comment by alescdb** [comment]
It may be related to #228 because when switching  to another app and come back it's enabled.

**Comment by rhansby** [comment]
You're correct, the paste button is disabled before you enter your password and the SSH session opens:
https://github.com/connectbot/connectbot/blob/master/app/src/main/java/org/connectbot/ConsoleActivity.java#L900

But after the session opens, the paste button is not being re-enabled.

**Comment by rhansby** [comment]
I am very sure that #297 finally fixes all issues with the paste button, but please verify.
