### ISSUE TITLE
Different icon for debug version of ConnectBot

### ISSUE THREAD

**Issue by kruton** [connectbot/connectbot#299]
Since the debug version of ConnectBot is named differently (`org.connectbot.debug` vs. `org.connectbot`), it would be nice to have a different icon for that version to visually indicate on recents and in the app launcher during development.

Simply placing the icon with the debug indicator in `app/src/debug/res/drawable-*/icon.png` should solve this without changing anything else.

The new icon could be generated with a scheme script from the `connectbot/assets` project for repeatability.

**Comment by wp9015362** [comment]
Speaking of it, would there be any chance you could put something like a Debug/Daily/Alpha/Beta version on the Google Play Store?

**Comment by alescdb** [comment]
Publishing beta apk could be achieved programmatically with Google Play Developer API.
Maybe with a bash/curl script, or with a java program.
This could be an idea for publishing "Untested builds" in beta on the Play Store without additional human interaction.

https://developers.google.com/android-publisher/tracks
