### ISSUE TITLE
Going into recents and back into connectbot switches active terminal

### ISSUE THREAD

**Issue by jklein24** [connectbot/connectbot#301]
Repro:
1) Open 2 connections.
2) Scroll to the second one.
3) Open recents and click connectbot again.

Notice that the open terminal has switched, but that typing does nothing (it's typing on the other terminal still.). Every time you repeat step 3, the terminal switches.

**Comment by jklein24** [comment]
This is starting to look like a bug in ViewPager. The problem is that setCurrentItem is called twice very quickly: at initialization it's called to set the selected page to 0, which triggers a scroll back to the beginning. Then there's a call to set it to 1 to restore previous state. The first call starts a scroll to the first page, but that call isn't actually executed by the time the second call rolls around and so this if statement evaluates to true:

https://github.com/android/platform_frameworks_support/blob/master/v4/java/android/support/v4/view/ViewPager.java#L836

which causes an early return. This is a race condition caused by the fact that scrolling happens asynchronously. It can probably be easily reproducible by just selecting the second page of a view pager and calling

`setCurrentItem(0); setCurrentItem(1);`

This should result in the second page showing, but will actually show the first.

**Comment by jklein24** [comment]
I can fix this by wrapping the call to setDisplayedTerminal in a pager.post() call, but it looks pretty janky because you can visibly see the pager scroll away and come back to the second page :-/

**Comment by jklein24** [comment]
To follow up on the note above, it looks like when `completeScroll` is called, the scroller already has the x coordinate for the first page, so the scroll just goes there instead of the second page.

https://github.com/android/platform_frameworks_support/blob/master/v4/java/android/support/v4/view/ViewPager.java#L1831

**Comment by alescdb** [comment]
I had bugs in one of my apps, I lost a lot of time on it until I discover it was a bug in v23.0.+ appcompat (https://code.google.com/p/android/issues/detail?id=183127).
Maybe you should start by upgrading v23.1.+, this may or may not help :-)

**Comment by jklein24** [comment]
I just tried that, but it seems that the problem still exists. Definitely a good suggestion, though :-).

**Comment by jklein24** [comment]
I guess I'll close this out, but I'll keep an eye on the internal ViewPager bug to switch to a better fix when that's available.
