### ISSUE TITLE
Host creation view dropdowns are non-obvious

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#312]
It's not possible to tell that certain dialog elements are dropdowns, e.g. "Protocol" and "Color category":

![unclear](https://cloud.githubusercontent.com/assets/1788374/10649818/ec8b3dbe-77fa-11e5-8435-d46b63e68731.png)

**Comment by khorimoto** [comment]
Any suggestion for what should be done to make it clearer? These are just the mocks that I was given.

**Comment by jklein24** [comment]
Maybe a dropdown arrow on the right?

**Comment by khorimoto** [comment]
@johnheroy, wanna take this?

**Comment by rhansby** [comment]
As discussed offline that this is standard UX for other apps, should this issue be closed?

**Comment by jklein24** [comment]
Yeah I think this is fine to close out.
