### ISSUE TITLE
Host creation: font size slider value does not update when focused

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#315]
When the user is focused on the value of the font size, dragging the slider does not change the value. 

GIF included:
![output](https://cloud.githubusercontent.com/assets/1788374/10650036/2e47dd7e-77fc-11e5-929b-636f95d80f07.gif)

**Comment by jklein24** [comment]
@johnheroy, want to check this out?

**Comment by johnheroy** [comment]
Sure! I'll check it out.
