### ISSUE TITLE
Host creation: faded FAB

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#316]
If you begin to create a host, but then go back and discard changes, the FAB is faded and seems disabled (it is not disabled).

Screenshot:
![faded](https://cloud.githubusercontent.com/assets/1788374/10650372/f0938a9e-77fd-11e5-8c55-b675b979a52e.png)

**Comment by khorimoto** [comment]
@johnheroy, wanna take this?

**Comment by johnheroy** [comment]
yup :)
