### ISSUE TITLE
Host creation cancellation dialog uses incorrect colors

### ISSUE THREAD

**Issue by rhansby** [connectbot/connectbot#317]
![bad color](https://cloud.githubusercontent.com/assets/1788374/10652968/a9b0c058-780f-11e5-97f1-3f30d955648c.png)

**Comment by khorimoto** [comment]
@johnheroy, wanna take this?

**Comment by alescdb** [comment]
Also would it be possible to unlink the user@host:port field and the nickname field if nickname has been set by user ?
When I just want to correct something in the host this erase my custom server nickname with the default one.
