### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#342]
Hello,

I am wondering:

Why has there not been a new release of ConnectBot yet?

I mean, all "MVP" labeled issues are closed now and ConnectBot has received a huge Material Design overhaul.

So, why not do a new release?

Could you please put up a new release?

Regards

**Comment by wp9015362** [comment]
@bengolds @kruton @rhansby @jklein24 @khorimoto :

Is there any specific reason why there is no more activity here in this repo for the last few weeks?

Regards

**Comment by kruton** [comment]
I was hoping to get more translations before the release, but it seems that only Japanese will have the new strings. The other reason is I need to create a new APK of the old version with maxSdkVersion set.

**Comment by JasperWeiss** [comment]
The latest release on f-droid is a few months old. I can't wait to see a new release.

**Comment by jklein24** [comment]
Friendly ping :-) - @kruton do we have enough translations yet?

**Comment by JasperWeiss** [comment]
I could help with the Dutch translations

**Comment by leonerd** [comment]
I've been playing around with a dev build of 1.9.0-alpha1 on my Galaxy Nexus and I definitely do not think it is ready for release yet. There are several regressions, things that are worse than 1.8.1. I'll write some bugs on those shortly.

**Comment by wp9015362** [comment]
@kruton & @jklein24 :

Any chance you could get https://github.com/connectbot/connectbot/issues/346 into 1.9 before releasing it?

**Comment by jklein24** [comment]
@leonerd, what were the bugs that you consider blocking for this release?

**Comment by leonerd** [comment]
@jklein24 Primarily, on my Galaxy Nexus, the "autohide" feature is completely broken. If you opt to hide the title bar, you can't ever display it again. It just doesn't reappear. I keep meaning to write a proper bug for it - I'll do that then link it here.

**Comment by jklein24** [comment]
Ok, great. Thanks!

**Comment by trygveaa** [comment]
@leonerd: Does #375 solve your problem?

**Comment by jklein24** [comment]
Ping again on this. It's been a pretty long time. @leonerd and @kruton, have your concerns been addressed?

**Comment by leonerd** [comment]
Ooh, I'll retest it after 375 then.

**Comment by jklein24** [comment]
Hey @leonerd, have you been able to test this again? I'd really like to see the months worth of work on this pushed out to the public. It's certainly a major net positive in terms of usability.

**Comment by leonerd** [comment]
Not yet. Unlikely before Monday at this rate, though maybe if I can have a quick 30second reminder of how I checkout/build/install it on a device I can take a look.

**Comment by jklein24** [comment]
You can grab the most recent alpha apk from https://github.com/connectbot/connectbot/releases/download/git-v1.9.0-alpha1-22-g31aa10b/ConnectBot-git-v1.9.0-alpha1-22-g31aa10b.apk. However, @kruton just warned me that https://github.com/connectbot/connectbot/pull/373 may have broken something with hostkeys where it always asks you to confirm. Apart from that, let us know if everything looks good.

**Comment by trygveaa** [comment]
In addition to #380 (which is the issue for what @jklein24 mentioned in the previous commit), I think #376 should probably be fixed before a release (both is regressions from the current release).

**Comment by JasperWeiss** [comment]
I love the new design :)

**Comment by wp9015362** [comment]
@kruton @jklein24 @bengolds @rhansby @khorimoto :

Any update? 1.9.0-alpha1 was released almost a year ago... Do you really wanna let all the commits rot on GitHub forever? How about calling it version 2.0 and releasing it with the new Material design now and calling it a day?

:stuck_out_tongue_winking_eye:

**Comment by jklein24** [comment]
+1. @kruton is the only one who can make the release, though. It's been 1 year and 634 commits since the last release. I agree it's time :-).

**Comment by kq01526** [comment]
@jklein24 :

Looks like @kruton has released yet another alpha:

https://github.com/connectbot/connectbot/commit/25351427af999f65d843801a08007172e7baa010

:yum: 

Time to do a new stable release IMHO.

And would make more sense to call it 2.0 instead of 1.9.0 IMHO.

**Comment by wp9015362** [comment]
@jklein24 :

Looks like @kruton has released yet another alpha:

https://github.com/connectbot/connectbot/commit/25351427af999f65d843801a08007172e7baa010

:yum:

Time to do a new stable release IMHO.

And would make more sense to call it 2.0 instead of 1.9.0 IMHO.

**Comment by jklein24** [comment]
agreed

**Comment by chirlu** [comment]
Any news? It's really annoying to use the old version without virtual cursor etc. keys on a newish phone that doesn’t have a trackball …

**Comment by kruton** [comment]
There's a problem with the new TextView overlay when trying to copy text. It will scroll by one row often and then it makes the terminal unusable. I haven't pinpointed the cause yet.

**Comment by wp9015362** [comment]
Closing this, since 1.9.x has been released now. Thanks.
