### ISSUE TITLE
Keypairs should not be backed up by default

### ISSUE THREAD

**Issue by cruvolo** [connectbot/connectbot#351]
I recently moved to a new device and was surprised to see my keypairs show up on the new device with no action taken on my part.  This means that keys were sent to google and only the key passphrase was protecting them. I consider this a security vulnerability.

Keypair backup should be disabled by default.  Users should be warned when enabling keypair backup that their keys are being disclosed and the potential for passphrase weaknesses.

Keypair backups are performed here:

https://github.com/connectbot/connectbot/blob/master/app/src/main/java/org/connectbot/service/BackupAgent.java#L47

		FileBackupHelper pubkeys = new FileBackupHelper(this, "../databases/" + PubkeyDatabase.DB_NAME);
		addHelper(PubkeyDatabase.DB_NAME, pubkeys);

**Comment by jklein24** [comment]
Keep in mind this is only backing up the *public* keys. However, I could still see reasoning for wanting to avoid that.

@kruton for input.

**Comment by cruvolo** [comment]
Private keys live in this SQLlite DB as well.  See PubkeyDatabase class.  https://github.com/connectbot/connectbot/blob/master/app/src/main/java/org/connectbot/util/PubkeyDatabase.java

**Comment by storm32** [comment]
I encountered this same problem.  I was shocked to see my private keys on my new Android device realizing third parties, Google in this case, had access to my keys.  

I agree with cruvolo where keys should not be backed up by default.

**Comment by cruvolo** [comment]
Thank you for addressing this.
