### ISSUE TITLE
Remember passwords

### ISSUE THREAD

**Issue by lcharles123** [connectbot/connectbot#355]
Has as implement it? A password with reasonable security has a great amount of characters, it is difficult to type on touch screen.

**Comment by leonerd** [comment]
This is what keys are for. Create a public/private keypair on the device, then send the public part to the server to add in the `.ssh/authorized_keys` file. You can then protect the private half with a short passphrase which is easier and more convenient to type locally on the device.

**Comment by oneru** [comment]
@leonerd While your answer is technically correct, an option to save passwords would be useful.

**Comment by abmantis** [comment]
@leonerd An option to save the password for the private key would also be nice, or protect it with fingerprint or a PIN, for example, which is quicker then typing the whole key password.

**Comment by leonerd** [comment]
@abmantis - why bother? That's equivalent to just not having a passphrase on the key at all in that case, which is already supported (though from a security perspective not really recommended).

If you think the passphrase is too long, make it shorter.

**Comment by abmantis** [comment]
@leonerd not really equivalent. The key file can be copied and then used anywhere, so I want to have a good password in it. Having ConnectBot remember the password, will only allow access if using the phone. 
For example, a malicious app could read the key file from the sdcard or internal partition, and use it if it has no password, but would not be able to do anything if ConnectBot stores the password in its app storage (which needs the right permissions to be accessed).

**Comment by abmantis** [comment]
@leonerd still not convinced with my argument? :P

**Comment by LevizX** [comment]
Many of us don't have the choice. I'm not the admin, I can't change the password - which is public knowledge. Why not add a simple option of just save the damn password?

**Comment by dimmuboy** [comment]
@LevizX is right. For same reason we're not capable to create key authentication.

**Comment by atiris** [comment]
I found that [JuiceSSH](<https://juicessh.com/>) is a good substitute for ConnectBot on Android and you can save your login data very well.

**Comment by hockeymikey** [comment]
> I found that [JuiceSSH](https://juicessh.com/) is a good substitute for ConnectBot on Android
> and you can save your login data very well.

Only wish it was FOSS. Don't know why this isn't a feature. Users can ignore it if they don't want it.

**Comment by KaKi87** [comment]
+1

**Comment by TarcisioMenezes** [comment]
+1

**Comment by ballerbude** [comment]
+10

Man, this situation is perfect example of one of the biggest downsides of FOSS software. This is such a basic functionality.
