### ISSUE TITLE
Feature Request: Passphrase Storage

### ISSUE THREAD

**Issue by roubert** [connectbot/connectbot#356]
It would be nice if it were possible to store the passphrase for a key in ConnectBot so that the key can be loaded into memory automatically.

(If the passphrase is stored properly, a key with such a stored passphrase would be better protected than a key without any passphrase but equally convenient to use.)

**Comment by leonerd** [comment]
This seems to defeat the very security properties that a passphrase gives to a key. ConnectBot already allows you to store passphrase-less keys if you so wish.

The security that the passphrase adds is that anyone who discovers your phone and manages to unlock the UI cannot yet use the stored keys, without also knowing that passphrase. If CB were to apply it automatically, that would be no better than a key without a phrase at all. I don't therefore see what this feature would buy.
