### ISSUE TITLE
connection on startup

### ISSUE THREAD

**Issue by barscm** [connectbot/connectbot#357]
When I power on my android device, connectbot (I assume; I have no other ssh clients installed (that I know of)) is attempting to connect to my server.

I see an entry on the server like:
Dec 23 10:23:01 {hostname} sshd[27780]: Did not receive identification string from {android_device_ip_address}

I can only infer that connectbot is trying to ping the device list on startup without a user request. I don't think a connect request is the best way to verify the list. Why this needs to be done at all, let alone on startup is also a mystery.

**Comment by kruton** [comment]
No, this is not ConnectBot. ConnectBot does not have any BOOT hooks that would start it when you start the device.

That type of error usually comes from monitoring software such as Zabbix, Nagios, or others.
