### ISSUE TITLE
Keyboard does not open when pressing keyboard button

### ISSUE THREAD

**Issue by trygveaa** [connectbot/connectbot#376]
When pressing the keyboard button on the virtual keyboard row, the soft keyboard does not open (most of the time, see next paragraph). The only thing that happens is that the virtual keyboard row hides.

If you open a new session, close the soft keyboard and press the keyboard button before the virtual keyboard row hides for the first time, the button actually works and the soft keyboard opens again. However if the virtual keyboard row has been hidden at least once, the button does not work.

This is with the current newest master (c9682d3). The error seems to have been introduced by 381c4b6.

**Comment by kruton** [comment]
I think this is because `TerminalView` was changed from `TextView` to just `View` which breaks the [forced showing of the keyboard](https://github.com/connectbot/connectbot/blob/381c4b65027c62fa87db6038fe6de5f4e46fe990/app/src/main/java/org/connectbot/ConsoleActivity.java#L568).

**Comment by jklein24** [comment]
Hmm... @kruton do you have any solution in mind for this? I'm happy to try to patch a fix in since @rhansby is out of town.

**Comment by oneru** [comment]
Not sure if related, but on the latest beta the terminal is sometimes hidden behind the keyboard.  To replicate, connect, run "ls" or similar command so the screen fills with text, then tap on the terminal.  The keyboard isn't hidden, but the text moves behind it, hiding the bottom rows of text.  Observed on an Nvidia shieldtablet.

**Comment by alescdb** [comment]
Same as @oneru here except I've got an FC every time I touch the console:

06-06 06:19:03.210  8254  8254 E AndroidRuntime: FATAL EXCEPTION: main
06-06 06:19:03.210  8254  8254 E AndroidRuntime: Process: org.connectbot, PID: 8254
06-06 06:19:03.210  8254  8254 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=127; index=127
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.indexAndLength(AbstractStringBuilder.java:207)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:201)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at java.lang.StringBuilder.charAt(StringBuilder.java)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at org.connectbot.util.TerminalTextViewOverlay.refreshTextFromBuffer(TerminalTextViewOverlay.java:83)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at org.connectbot.util.TerminalTextViewOverlay.onTouchEvent(TerminalTextViewOverlay.java:174)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9300)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9520)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-06 06:19:03.210  8254  8254 E AndroidRuntime: 	at java.lang.reflect.Method.invo
06-06 06:19:03.212  1380  2102 W ActivityManager:   Force finishing activity org.connectbot/.ConsoleActivity
`

**Comment by alescdb** [comment]
Fixed for me in git-v1.9.0-alpha1-90-g560f894
Sorry

**Comment by kruton** [comment]
Yeah, different bug I just introduced. Should be fixed with #414 and #415.

**Comment by oneru** [comment]
I observed the problem I described in the git-v1.9.0-alpha1-90-g560f894 apk.
