### ISSUE TITLE
Doesn't remember host keys

### ISSUE THREAD

**Issue by trygveaa** [connectbot/connectbot#380]
The first time I connect to a host with ssh, I get the message "The authenticity of host '\<domain\>' can't be established" and the question "Are you sure you want to continue connecting". This is normal.

However, with the newest master, this appears every time I connect to a host. Even though I select yes and establish a connection, the question reappears the next time I try to connect. I can't find any way to get ConnectBot to remember this selection.

This is with a self built version of the currently newest master, 388a056.

**Comment by kruton** [comment]
Hmm, must be a mismatch with sshlib. Thanks for the report.
