### ISSUE TITLE
README for developers - why does the app utilize NDK / native code?

### ISSUE THREAD

**Issue by RoundSparrow** [connectbot/connectbot#382]
I know the app has a long history - but looking at the source code, I'm not entirely clear why NDK / native code requirement exists.  Is there a library I'm not recognizing as native code?  Some particular bug in Java sockets of Android that going to c or c++ resolves?

Thank you.

**Comment by kruton** [comment]
Local shell requires native code to create a pty. The code for that is [here](https://github.com/connectbot/connectbot/blob/master/app/src/main/jni/com_google_ase_Exec.cpp#L80).

**Comment by RoundSparrow** [comment]
Ok, thank you.
