### ISSUE TITLE
Misuse of setShowAsAction(int)

### ISSUE THREAD

**Issue by frankFic** [connectbot/connectbot#394]
Dear developer of connectbot,

I have found that you used 
menu.add(0, COPY, 0, R.string.console_menu_copy).setShowAsAction(MenuItem.SHOW_AS_ACTION_WITH_TEXT | MenuItem.SHOW_AS_ACTION_IF_ROOM);
on line 356 in org.connectbot.util.TerminalTextViewOverlay.

However method setShowAsAction(int) was introduced in API 11([API guide](http://developer.android.com/intl/zh-cn/reference/android/view/MenuItem.html#setShowAsAction(int))). 
Although the warning is suppressed by @TargetApi(11), it can still cause crash on devices with API level prior than 11.

It would be better if it is fixed by checking the SDK version of the device before invoking this method like stated in [android developers training](http://developer.android.com/training/basics/supporting-devices/platforms.html#sdk-versions).

Hope this is useful. :)

Thank you.

**Comment by kruton** [comment]
That is called in onCreateActionMode which is only called starting in API
11, so there appears to be no problem.
