### ISSUE TITLE
no changelog on fdroid

### ISSUE THREAD

**Issue by treakiandroid** [connectbot/connectbot#399]
Please add an version changelog to the fdroid repo.

Thanks

**Comment by treakiandroid** [comment]
!(http://treaki.tk/upload/uploads/1463610433/screenshot-1463609531937.png)
As you can see no changelog at all

**Comment by mrc0mmand** [comment]
I guess you have an old version of fdroid. Newer versions have a subset of links, where one of them points directly to the [changelog](https://sumsal.cz/img/Screenshot_2016-05-19-00-44-20.png).

**Comment by kruton** [comment]
I don't control fdroid.
