### ISSUE TITLE
keys generated using CB shows parsing error when imported on other device

### ISSUE THREAD

**Issue by abinashdash17** [connectbot/connectbot#429]
First i generated rsa 2048 key on my 1st device without any passphrase using CB. Then copied the private key to clipboard and created a file `rsa_id`. No error showed up when i imported the key using pub key manager.

But when i transferred the file to 2nd android device and tried to import the keys 'problem parsing imported private keys ' error showed up..

Both android devices are using same version of connectbot.
Is it a bug or am i doing something wrong?

**Comment by kruton** [comment]
How are you transferring the private keys?

**Comment by abinashdash17** [comment]
Tried both bluetooth and wifi(xender). None of them worked.

**Comment by kruton** [comment]
I mean how are you exporting the private keys that were generated in ConnectBot? As far as I recall, that is not enabled.

**Comment by abinashdash17** [comment]
1 more thing. bluetooth didn't allowed file w/o extension so i renamed it to rsa_id.txt and then again renamed back to rsa_id.

**Comment by abinashdash17** [comment]
I'm copying the private key and pasting it to a file.

**Comment by abinashdash17** [comment]
Manage pub key->generated key menu->'copy private key'

**Comment by kruton** [comment]
Ah, it looks like importing it is generating an `RSAPrivateKey` and it should be generating an `RSAPrivateCrtKey`.
