### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by treakiandroid** [connectbot/connectbot#45]
Where can i find a changelog??

**Comment by ckujau** [comment]
Try the [commit log](https://github.com/connectbot/connectbot/commits/master).

**Comment by treakiandroid** [comment]
thanks for that advice. thats better then nothing but a changelog which would group together all actually changes of the stable releases would also be nice.

**Comment by tomswartz07** [comment]
I agree.

It also does not help that [some of the commits](https://github.com/connectbot/connectbot/commit/fc0fd37d666bb8bd1452c2263cd6fdcf652230cd) are pretty cryptic as to what they actually *do*...

**Comment by nyuszika7h** [comment]
@tomswartz07 That's just an internal refactor, it doesn't affect functionality.

**Comment by kruton** [comment]
It would help with market releases.
http://keepachangelog.com/

**Comment by kruton** [comment]
Okay, submitted 448addf10d132a410b7d280674fef5ed04463ed2 which adds CHANGELOG.md

**Comment by kruton** [comment]
The latest URL is always https://github.com/connectbot/connectbot/blob/master/CHANGELOG.md
