### ISSUE TITLE
Older versions request

### ISSUE THREAD

**Issue by stairway2heaven** [connectbot/connectbot#456]
Hi,

The project has been used as part of an experiment previously for an IEEE paper. We are currently trying to recreate the experiment but would require the later commits for version 1.7.1 to do so. The history after October 2010 is currently not visible. Is there any possibility to get access to this ? Any help would be much appreciated.

**Comment by kruton** [comment]
The entire history of the project is in git. Each release is also tagged. https://github.com/connectbot/connectbot/releases/tag/v1.7.1

The actual build may still be available for download from the [old Google Code page](https://code.google.com/archive/p/connectbot/downloads?page=5).
