### ISSUE TITLE
Try all addresses for a host (including IPv6/IPv4)

### ISSUE THREAD

**Issue by raoulbhatia** [connectbot/connectbot#46]
When you are on a network with broken IPv6 but working IPv4 routing, connecting to a dual stack host via DNS fails because IPv6 is prefered.

I had to manually connect to the IPv4 address to establish the connection.

It would be nice to have

a) a global and/or per host setting to specify i.e. IPv4 only host
b) maybe a long click option "Connect via IPvX this time only"

What do you think?
Raoul

**Comment by ckujau** [comment]
Thanks! (GitHub is missing a "Like" or "Thanks" button or something like that :-))

**Comment by kruton** [comment]
I still think there are issues with IPv6 but it's difficult to tell where in the stack it's failing currently. Test it out, though.

**Comment by roughnecks** [comment]
Sorry for opening this one up again.

I'm trying to connect to a host which resolves to both A and AAAA records and my problem is that I want to connect via IPv4, while ConnectBot only tries IPv6 and fails.
Is it just me? Thanks

**Comment by Don9999** [comment]
Same issue here, ConnectBot seems to be trying to connect to an IPv6 address and failing when there should be none defined, at least that I am aware of. Need to be able to force an IPv4 address.

Don

**Comment by rfkd** [comment]
As already mentioned before I can confirm this problem in v1.9.2 as well. The issue should be reopened.
