### ISSUE TITLE
Passwordless SSH Keys cached in ConnectBot, can get backed up to Google servers

### ISSUE THREAD

**Issue by CaptainRewind** [connectbot/connectbot#462]
Hello,

I recently migrated Android devices.  I used Google's migration assistant.  On the old device, I had SSH keys with no password stored on the SD card, which I had imported into ConnectBot.  After migrating, I noticed that I was able to login to my servers just fine, with no password (and the SSH keys were NOT saved on the SD card of the new device).  I would have expected a message like "key not found on device," but it would seem that importing keys into ConnectBot actually copies the key into the app data ... I would have expected that process to be more akin to a symlink or some similar.

Obviously, I rotated all my keys immediately upon learning this. Also, I am using only password-protected keyfiles now, and am not backing up this app to Google servers anymore.  Still, it would be nice to have this corrected in the application itself if possible, particularly for future users who might not notice the risk this poses.

Thanks!

**Comment by kruton** [comment]
This is fixed in Release 1.9.0.
