### ISSUE TITLE
Import ssh keys doesn't work

### ISSUE THREAD

**Issue by ambrosa** [connectbot/connectbot#465]
Some days ago I've installed Connectbot 1.8.6 in my new Lenovo TAB3 Plus tablet (Android 6.0.1).
It works very fine.
With ConnectBot I've generated a new RSA pair priv/pub key. Then I've imported the pub key into my remote Linux systems and SSH connection from ConnectBot to remote Linux systems works fne.

I've made a tablet factory reset and then reinstalled ConnectBot.
I choose to import the priv key previously generated but app tell me that there was a problem during importing.
I've installed ConnectBot in my smarphone Sony Xperia Z3 (Android 6.0.1) and I've the same import problem.
Reading the content of priv text file , it looks correct.

Any idea ?

**Comment by kruton** [comment]
This was probably fixed by db3a2a95bbc88f3ecda3e91d534e6c962fd02530 which was included in Release 1.9.0.
