### ISSUE TITLE
 1.9.1 - Unintended Scrolling

### ISSUE THREAD

**Issue by michaelof** [connectbot/connectbot#476]
After upgrading to 1.9.1 connectBot unfortunately has become nearly unusable for me.

When opening or closing the virtual keyboard, connectBot scrolls to somewhere, reason and target not comprehensible. No chance to scroll back to current (bash) input line by wiping. Sometimes, not always, reopening keyboard and starting to type will "refocus" to input line. Not always, sometimes you have to type blind/invisible and earliest get the cursor/focus back after pressing enter - not usable, a pity.
Setting "additional keys always visible" (translated back from German) helps a little, but not really.

Would be great to get this fixed, I love connectBot!

**Comment by Wojbie** [comment]
After testing on 2 different I can confirm the issue.

In seems to me it scrolls up to size screen would be with keyboard off even when keyboard is on screen.

**Comment by kruton** [comment]
Hm, I have seen this before, but I can't reliably reproduce it. Do you have any sure-fire ways to reproduce?

**Comment by michaelof** [comment]
All I can say that it's 100% reproducible on my Android. And it's "introduced" with 1.9.1. I'm using connectBot for years now, never seen before.

As I've never developed anything for/on Android, do you have any ideas how we could "sure-fire" this? Any chance to trace/debug/log GUI activity?

**Comment by Wojbie** [comment]
Reproduction steps for me:

Using portrait mode. Did not think to test in landscape sorry.

1. Connect to host
2. Do actions that make screen have some lines... just to there is scrollable stuff
3. Tap screen
4. Screen contents now scroll up about x lines and get stuck like that place was bottom of screen.

Amount of lines depends of setup:
autohide top bar is on
special keys always visible is on
Scrreen sizes: keyboard: 60x25 no keyboard 60x41
goes up 4 lines

autohide top bar is on
special keys always visible is off
Scrreen sizes: keyboard: 60x27 no keyboard 60x43
goes up 4 lines

autohide top bar is off 
special keys always visible is on
Scrreen sizes: keyboard: 60x23 no keyboard 60x37
Goes up 4 lines

autohide top bar is off 
special keys always visible is off
Scrreen sizes: keyboard: 60x20 no keyboard 60x39
Goes up 6 lines

**Comment by kruton** [comment]
Ah, okay, I just tried it with 1.9.1 and could reproduce it.

However, I've been testing with the latest revision. After merging #475 I can't reproduce it. The "event was handled" signal wasn't propogating correctly until I fixed it for pg-up/pg-down gesture in 787f5d4323dbf88d5b9a9f010f611bc12987ca74.

**Comment by Wojbie** [comment]
Darn... and i just recorded a nice video of glitch for you just now.
So this is fixed?
Great!

**Comment by michaelof** [comment]
Cool, thanks to both of you! I'll wait for an update on F-Droid then.

Great!

**Comment by kruton** [comment]
You can try the signed version here: https://github.com/connectbot/connectbot/releases/tag/git-v1.9.1-25-gd4537fa

However, F-Droid re-signs the binaries, so this probably won't work.

**Comment by Wojbie** [comment]
I can confirm that this version fixed the bug for me. Thank you.

**Comment by ehashman** [comment]
Just another +1 for this bug report. Really easy way to reproduce is to launch irssi or other full-screen terminal apps. I'm using the Google Play store version (and will wait until that's released there to upgrade).

Thanks!

**Comment by michaelof** [comment]
Just a question: Any ideas when the fix will be included in a new F-Droid package?
