### ISSUE TITLE
Settings change apparently randomly

### ISSUE THREAD

**Issue by goldencut** [connectbot/connectbot#480]
While scrolling up and down in Settings menu  offscreen settings change randomly making it impossible to save settings the way one wants. Huawei Honor 4C, Andr.4.4.2

**Comment by kruton** [comment]
Have you had this on any other app? The new Settings screen is using the Android compatibility library's `AppCompatPreferenceActivity`, so it would probably be the same with other apps.

**Comment by goldencut** [comment]
First time I've seen this kind of behavior. :/ Should this AppCompat...-thing work on Android 4.4.2?

**Comment by kruton** [comment]
Yes, it should. It looks like #482 has a similar issue. It may just be a bug that has been fixed in [recent versions of the support library](https://developer.android.com/topic/libraries/support-library/revisions.html).

**Comment by goldencut** [comment]
Will there be a release in F-Droid with this patch in near future?

**Comment by kruton** [comment]
I don't control F-Droid releases or the content of them.
