### ISSUE TITLE
UI usability issues with v1.9.x

### ISSUE THREAD

**Issue by virtualdj** [connectbot/connectbot#482]
Hi, a couple of days ago the Google Play Store updated my ConnectBot version 1.8.7 to 1.9.1 I think (I had to uninstall it later, due to the #476 bug).
I have to be honest to tell you that I don't link this "material" UI very much, especially the icons on the left of the hosts in the main activity. Version 1.8.x was very very neat instead, more professional looking.

But I'm writing here because of the **settings/preferences**, as I don't think this UI is correct.
Take a look of the following screenshots:

![settings1](https://cloud.githubusercontent.com/assets/3251704/23139183/6bcd7da4-f7ab-11e6-9b1b-72d7f8dc431f.png)

It seems that there are new line breaks into the text, or either the View size is wrong.
It's very very ugly!

And also, as you can see here:

![settings2](https://cloud.githubusercontent.com/assets/3251704/23139210/929dbd40-f7ab-11e6-972c-7913ec7b166e.png)

There are two types of ON/OFF buttons mixed in a random way.
The 1.8.x version was perfect:

![settings_old](https://cloud.githubusercontent.com/assets/3251704/23139236/add3d612-f7ab-11e6-82d9-c947f831063e.png)

... so I had to roll back. But is this something _temporary_? I hope so!

Also it would be great to have the virtual keyboard with the special keys (CTRL, ESC, TAB, cursors, etc.) to remain on the screen a bit more, because sometimes it's very difficul to type several TABs on autocompletion, as your finger is actually **over** the text that is being autocompleted (see below).

![tab](https://cloud.githubusercontent.com/assets/3251704/23139287/f64f7bc6-f7ab-11e6-933a-6817db5f121f.png)

Thanks!

**Comment by kruton** [comment]
Thanks for the detailed feedback. I agree the settings look bad in your screenshots. Can you tell me what type of phone and what OS version it's running?

**Comment by virtualdj** [comment]
Yes, of course. It's a Samsung Galaxy Note 4 with Android KitKat v4.4.4.
I somewhat forget to include this information, sorry!

**Comment by kruton** [comment]
Okay, #487 fixes the way the preferences looks. Unfortunately some of the Italian translations are too long to fit on the screen still.

Screenshots from a 4.1.2 emulator:

<img width="369" alt="screen shot 2017-02-23 at 7 27 48 am" src="https://cloud.githubusercontent.com/assets/50407/23265555/d9318d32-f999-11e6-93d1-5d9b2e40c0d9.png">

<img width="367" alt="screen shot 2017-02-23 at 7 28 17 am" src="https://cloud.githubusercontent.com/assets/50407/23265542/cc9babd4-f999-11e6-89ab-df7c0d659d37.png">

**Comment by virtualdj** [comment]
Thanks, looks great now and on my device (it's the same than on the emulator)!
P.S.: I'll look if I can contribute by shortening the Italian translation if I find some spare minutes whenever possible!
