### ISSUE TITLE
Selecting text doesn't work in 1.9 anymore 

### ISSUE THREAD

**Issue by ervee** [connectbot/connectbot#485]
Hi, 

The new 1.9 updates don't let me select text correctly anymore. When selecting text it looks like it is incorrectly selecting text from the line below where the select markers actually are. Also the magnifying thing isn't displaying anything useful.

Using version 1.9.1 from F-Droid on Sony Xperia Z5. Android 6.0.1.

**Comment by kruton** [comment]
I fixed a selection bug in 1.9.2. Please try that version and reply here if it doesn't fix it.

**Comment by ervee** [comment]
That version is not available on F-Droid yet. Uninstalled it and installed from Google Play store.
The selecting of text seems fine now, but the magnifier window still doesn't show anything useful.

**Comment by kruton** [comment]
I'm not sure what you mean by the magnifier window. Maybe this is a feature of the Xperia phone?

**Comment by ervee** [comment]
![screenshot_20170223-203120](https://cloud.githubusercontent.com/assets/4435930/23281906/53677104-fa1f-11e6-840b-b78cd535f504.jpg)

That.
