### ISSUE TITLE
Android 7.0 authentication with key isn't working

### ISSUE THREAD

**Issue by sjbird** [connectbot/connectbot#488]
=== update ===
Solved.
It is and it isn't.
Turns out that vendors keep dropping support for DSA kays. And apparently Android 7 has dropped it in comparison with Android 6.
Without going into details, I've changed my key from DSA to RSA and it works now.
====

I can not connect using the key from my Android 7 phone.
1) I can connect from three other android devices
2) I can connect from Android 7 device using password
3) I tried two different servers (Linux Fedora) 

It appears that ConnectBot on Android 7 successfully authenticates, and then immediately closing connection.
sshd[8110]: Connection closed by 192.168.1.116 port 44684 [preauth]
.116 - is my android 7 phone's IP (connectbot client)

I am sure I've setup everything corrrectly. I removed connectbot from my older phone and installed it back in, got the key imported and it works.
I am using Connectbot 1.9.2

Full log bellow. First section is unsuccessful attempt with the key. Then I unloaded the key from the memory and used exact same server entry to connect with the password.

Feb 23 21:47:42 lenovo sshd[7928]: debug1: Forked child 8110.
Feb 23 21:47:42 lenovo sshd[8110]: debug1: Set /proc/self/oom_score_adj to 0
Feb 23 21:47:42 lenovo sshd[8110]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Feb 23 21:47:42 lenovo sshd[8110]: debug1: inetd sockets after dupping: 3, 3
Feb 23 21:47:42 lenovo sshd[8110]: Connection from 192.168.1.116 port 44684 on 192.168.1.115 port 22
Feb 23 21:47:42 lenovo sshd[8110]: debug1: Client protocol version 2.0; client software version TrileadSSH2Java_213
Feb 23 21:47:42 lenovo audit[8111]: CRYPTO_KEY_USER pid=8111 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:38:1d:64:17:35:e3:43:ed:1b:77:67:fb:40:2b:55:f7:3b:a8:cd:0e:34:aa:5a:80:d6:8d:c2:86:8c:45:c2:16 direction=? spid=8111 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:42 lenovo sshd[8110]: debug1: no match: TrileadSSH2Java_213
Feb 23 21:47:42 lenovo audit[8111]: CRYPTO_KEY_USER pid=8111 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:30:2d:ee:42:f9:03:bf:9c:c9:1c:dd:da:a7:12:51:ea:19:2f:08:d6:d9:e7:4d:f0:90:bd:64:b8:1c:76:6a:de direction=? spid=8111 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:42 lenovo sshd[8110]: debug1: Enabling compatibility mode for protocol 2.0
Feb 23 21:47:42 lenovo audit[8111]: CRYPTO_KEY_USER pid=8111 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:87:26:e0:66:d1:62:57:5a:c2:9d:44:45:02:8e:1d:2b:0b:92:70:02:d8:e3:41:4d:ae:3a:c5:ef:c5:70:eb:cd direction=? spid=8111 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:42 lenovo sshd[8110]: debug1: Local version string SSH-2.0-OpenSSH_7.2
Feb 23 21:47:42 lenovo sshd[8110]: debug1: SELinux support enabled [preauth]
Feb 23 21:47:42 lenovo sshd[8110]: debug1: ssh_selinux_change_context: setting context from 'system_u:system_r:sshd_t:s0-s0:c0.c1023' to 'system_u:system_r:sshd_net_t:s0-s0:c0.c1023' [preauth]
Feb 23 21:47:42 lenovo sshd[8110]: debug1: permanently_set_uid: 74/74 [preauth]
Feb 23 21:47:42 lenovo sshd[8110]: debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
Feb 23 21:47:42 lenovo sshd[8110]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: SSH2_MSG_KEXINIT received [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: kex: algorithm: curve25519-sha256@libssh.org [preauth]
Feb 23 21:47:43 lenovo audit[8110]: CRYPTO_SESSION pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=start direction=from-server cipher=aes256-ctr ksize=256 mac=hmac-sha2-256 pfs=curve25519-sha256@libssh.org spid=8111 suid=74 rport=44684 laddr=192.168.1.115 lport=22  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:43 lenovo sshd[8110]: debug1: kex: host key algorithm: ssh-ed25519 [preauth]
Feb 23 21:47:43 lenovo audit[8110]: CRYPTO_SESSION pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=start direction=from-client cipher=aes256-ctr ksize=256 mac=hmac-sha2-256 pfs=curve25519-sha256@libssh.org spid=8111 suid=74 rport=44684 laddr=192.168.1.115 lport=22  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:43 lenovo sshd[8110]: debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32 [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32 [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: rekey after 4294967296 blocks [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
Feb 23 21:47:43 lenovo sshd[8110]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
Feb 23 21:47:44 lenovo sshd[8110]: debug1: rekey after 4294967296 blocks [preauth]
Feb 23 21:47:44 lenovo sshd[8110]: debug1: SSH2_MSG_NEWKEYS received [preauth]
Feb 23 21:47:44 lenovo sshd[8110]: debug1: KEX done [preauth]
Feb 23 21:47:44 lenovo sshd[8110]: debug1: userauth-request for user XXXXX service ssh-connection method none [preauth]
Feb 23 21:47:44 lenovo sshd[8110]: debug1: attempt 0 failures 0 [preauth]
Feb 23 21:47:44 lenovo sshd[8110]: debug1: PAM: initializing for "XXXXXX"
Feb 23 21:47:44 lenovo sshd[8110]: debug1: PAM: setting PAM_RHOST to "192.168.1.116"
Feb 23 21:47:44 lenovo sshd[8110]: debug1: PAM: setting PAM_TTY to "ssh"
Feb 23 21:47:44 lenovo sshd[8110]: Connection closed by 192.168.1.116 port 44684 [preauth]
Feb 23 21:47:44 lenovo sshd[8110]: debug1: do_cleanup [preauth]
Feb 23 21:47:44 lenovo audit[8110]: CRYPTO_KEY_USER pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:87:26:e0:66:d1:62:57:5a:c2:9d:44:45:02:8e:1d:2b:0b:92:70:02:d8:e3:41:4d:ae:3a:c5:ef:c5:70:eb:cd direction=? spid=8111 suid=74  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:44 lenovo sshd[8110]: debug1: monitor_read_log: child log fd closed
Feb 23 21:47:44 lenovo audit[8110]: CRYPTO_KEY_USER pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=session fp=? direction=both spid=8111 suid=74 rport=44684 laddr=192.168.1.115 lport=22  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:44 lenovo sshd[8110]: debug1: do_cleanup
Feb 23 21:47:44 lenovo audit[8110]: USER_ERR pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:bad_ident grantors=? acct="?" exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=ssh res=failed'
Feb 23 21:47:44 lenovo sshd[8110]: debug1: PAM: cleanup
Feb 23 21:47:44 lenovo audit[8110]: CRYPTO_KEY_USER pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:38:1d:64:17:35:e3:43:ed:1b:77:67:fb:40:2b:55:f7:3b:a8:cd:0e:34:aa:5a:80:d6:8d:c2:86:8c:45:c2:16 direction=? spid=8110 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:44 lenovo sshd[8110]: debug1: Killing privsep child 8111
Feb 23 21:47:44 lenovo audit[8110]: CRYPTO_KEY_USER pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:30:2d:ee:42:f9:03:bf:9c:c9:1c:dd:da:a7:12:51:ea:19:2f:08:d6:d9:e7:4d:f0:90:bd:64:b8:1c:76:6a:de direction=? spid=8110 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:44 lenovo audit[8110]: CRYPTO_KEY_USER pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:87:26:e0:66:d1:62:57:5a:c2:9d:44:45:02:8e:1d:2b:0b:92:70:02:d8:e3:41:4d:ae:3a:c5:ef:c5:70:eb:cd direction=? spid=8110 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 21:47:44 lenovo audit[8110]: USER_LOGIN pid=8110 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login acct="XXXXX" exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=ssh res=failed'

Successful log in with the password
Feb 23 22:19:36 lenovo sshd[7928]: debug1: Forked child 11947.
Feb 23 22:19:36 lenovo sshd[11947]: debug1: Set /proc/self/oom_score_adj to 0
Feb 23 22:19:36 lenovo audit[11948]: CRYPTO_KEY_USER pid=11948 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:38:1d:64:17:35:e3:43:ed:1b:77:67:fb:40:2b:55:f7:3b:a8:cd:0e:34:aa:5a:80:d6:8d:c2:86:8c:45:c2:16 direction=? spid=11948 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:36 lenovo sshd[11947]: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8
Feb 23 22:19:36 lenovo audit[11948]: CRYPTO_KEY_USER pid=11948 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:30:2d:ee:42:f9:03:bf:9c:c9:1c:dd:da:a7:12:51:ea:19:2f:08:d6:d9:e7:4d:f0:90:bd:64:b8:1c:76:6a:de direction=? spid=11948 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:36 lenovo sshd[11947]: debug1: inetd sockets after dupping: 3, 3
Feb 23 22:19:36 lenovo audit[11948]: CRYPTO_KEY_USER pid=11948 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:87:26:e0:66:d1:62:57:5a:c2:9d:44:45:02:8e:1d:2b:0b:92:70:02:d8:e3:41:4d:ae:3a:c5:ef:c5:70:eb:cd direction=? spid=11948 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:36 lenovo sshd[11947]: Connection from 192.168.1.116 port 44743 on 192.168.1.115 port 22
Feb 23 22:19:36 lenovo sshd[11947]: debug1: Client protocol version 2.0; client software version TrileadSSH2Java_213
Feb 23 22:19:36 lenovo sshd[11947]: debug1: no match: TrileadSSH2Java_213
Feb 23 22:19:36 lenovo sshd[11947]: debug1: Enabling compatibility mode for protocol 2.0
Feb 23 22:19:36 lenovo sshd[11947]: debug1: Local version string SSH-2.0-OpenSSH_7.2
Feb 23 22:19:36 lenovo sshd[11947]: debug1: SELinux support enabled [preauth]
Feb 23 22:19:36 lenovo audit[11947]: CRYPTO_SESSION pid=11947 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=start direction=from-server cipher=aes256-ctr ksize=256 mac=hmac-sha2-256 pfs=curve25519-sha256@libssh.org spid=11948 suid=74 rport=44743 laddr=192.168.1.115 lport=22  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:36 lenovo sshd[11947]: debug1: ssh_selinux_change_context: setting context from 'system_u:system_r:sshd_t:s0-s0:c0.c1023' to 'system_u:system_r:sshd_net_t:s0-s0:c0.c1023' [preauth]
Feb 23 22:19:36 lenovo audit[11947]: CRYPTO_SESSION pid=11947 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=start direction=from-client cipher=aes256-ctr ksize=256 mac=hmac-sha2-256 pfs=curve25519-sha256@libssh.org spid=11948 suid=74 rport=44743 laddr=192.168.1.115 lport=22  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:36 lenovo sshd[11947]: debug1: permanently_set_uid: 74/74 [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: SSH2_MSG_KEXINIT received [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: kex: algorithm: curve25519-sha256@libssh.org [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: kex: host key algorithm: ssh-ed25519 [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32 [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: kex: curve25519-sha256@libssh.org need=32 dh_need=32 [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: rekey after 4294967296 blocks [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: rekey after 4294967296 blocks [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: SSH2_MSG_NEWKEYS received [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: KEX done [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: userauth-request for user XXXXX service ssh-connection method none [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: attempt 0 failures 0 [preauth]
Feb 23 22:19:36 lenovo sshd[11947]: debug1: PAM: initializing for "XXXXX"
Feb 23 22:19:36 lenovo sshd[11947]: debug1: PAM: setting PAM_RHOST to "192.168.1.116"
Feb 23 22:19:36 lenovo sshd[11947]: debug1: PAM: setting PAM_TTY to "ssh"
Feb 23 22:19:43 lenovo sshd[11947]: debug1: userauth-request for user XXXXX service ssh-connection method password [preauth]
Feb 23 22:19:43 lenovo sshd[11947]: debug1: attempt 1 failures 0 [preauth]
Feb 23 22:19:43 lenovo audit[11947]: USER_AUTH pid=11947 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=pam_unix acct="XXXXX" exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=ssh res=success'
Feb 23 22:19:43 lenovo sshd[11947]: debug1: PAM: password authentication accepted for XXXXX
Feb 23 22:19:43 lenovo sshd[11947]: debug1: do_pam_account: called
Feb 23 22:19:43 lenovo audit[11947]: USER_ACCT pid=11947 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:accounting grantors=pam_unix,pam_localuser acct="XXXXX" exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=ssh res=success'
Feb 23 22:19:43 lenovo sshd[11947]: Accepted password for XXXX from 192.168.1.116 port 44743 ssh2
Feb 23 22:19:43 lenovo sshd[11947]: debug1: monitor_child_preauth: XXXX has been authenticated by privileged process
Feb 23 22:19:43 lenovo audit[11947]: CRYPTO_KEY_USER pid=11947 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=session fp=? direction=both spid=11948 suid=74 rport=44743 laddr=192.168.1.115 lport=22  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:43 lenovo sshd[11947]: debug1: monitor_read_log: child log fd closed
Feb 23 22:19:43 lenovo audit[11947]: USER_AUTH pid=11947 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=success acct="XXXXX" exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=ssh res=success'
Feb 23 22:19:43 lenovo sshd[11947]: debug1: temporarily_use_uid: 1000/1000 (e=0/0)
Feb 23 22:19:43 lenovo sshd[11947]: debug1: ssh_gssapi_storecreds: Not a GSSAPI mechanism
Feb 23 22:19:43 lenovo sshd[11947]: debug1: restore_uid: 0/0
Feb 23 22:19:43 lenovo audit[11947]: CRED_ACQ pid=11947 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_unix acct="XXXXX" exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=ssh res=success'
Feb 23 22:19:43 lenovo sshd[11947]: debug1: SELinux support enabled
Feb 23 22:19:43 lenovo sshd[11947]: debug1: PAM: establishing credentials
Feb 23 22:19:43 lenovo audit[11947]: USER_ROLE_CHANGE pid=11947 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='pam: default-context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 selected-context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=ssh res=success'
Feb 23 22:19:43 lenovo audit[1]: USER_AVC pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='Unknown permission start for class system exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
Feb 23 22:19:43 lenovo systemd-logind[951]: New session 5 of user XXXXX.
Feb 23 22:19:43 lenovo systemd[1]: Started Session 5 of user XXXXX.
Feb 23 22:19:43 lenovo sshd[11947]: pam_unix(sshd:session): session opened for user XXXXX by (uid=0)
Feb 23 22:19:43 lenovo audit[11947]: USER_START pid=11947 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,pam_selinux,pam_namespace,pam_keyinit,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_lastlog acct="XXXXX" exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=ssh res=success'
Feb 23 22:19:43 lenovo systemd[1]: Starting Session 5 of user XXXXX.
Feb 23 22:19:43 lenovo sshd[11947]: User child is on pid 11962
Feb 23 22:19:43 lenovo audit[11962]: CRYPTO_KEY_USER pid=11962 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:38:1d:64:17:35:e3:43:ed:1b:77:67:fb:40:2b:55:f7:3b:a8:cd:0e:34:aa:5a:80:d6:8d:c2:86:8c:45:c2:16 direction=? spid=11962 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:43 lenovo audit[11962]: CRYPTO_KEY_USER pid=11962 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:30:2d:ee:42:f9:03:bf:9c:c9:1c:dd:da:a7:12:51:ea:19:2f:08:d6:d9:e7:4d:f0:90:bd:64:b8:1c:76:6a:de direction=? spid=11962 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:43 lenovo audit[11962]: CRYPTO_KEY_USER pid=11962 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:87:26:e0:66:d1:62:57:5a:c2:9d:44:45:02:8e:1d:2b:0b:92:70:02:d8:e3:41:4d:ae:3a:c5:ef:c5:70:eb:cd direction=? spid=11962 suid=0  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'
Feb 23 22:19:43 lenovo sshd[11962]: debug1: PAM: establishing credentials
Feb 23 22:19:43 lenovo audit[11962]: CRED_ACQ pid=11962 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:setcred grantors=pam_unix acct="XXXXX" exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=ssh res=success'
Feb 23 22:19:43 lenovo sshd[11962]: debug1: permanently_set_uid: 1000/1000
Feb 23 22:19:43 lenovo sshd[11962]: debug1: rekey after 4294967296 blocks
Feb 23 22:19:43 lenovo sshd[11962]: debug1: rekey after 4294967296 blocks
Feb 23 22:19:43 lenovo sshd[11962]: debug1: ssh_packet_set_postauth: called
Feb 23 22:19:43 lenovo sshd[11962]: debug1: Entering interactive session for SSH2.
Feb 23 22:19:43 lenovo sshd[11962]: debug1: server_init_dispatch_20
Feb 23 22:19:43 lenovo sshd[11962]: debug1: server_input_channel_open: ctype session rchan 100 win 30000 max 33976
Feb 23 22:19:43 lenovo sshd[11962]: debug1: input_session_request
Feb 23 22:19:43 lenovo sshd[11962]: debug1: channel 0: new [server-session]
Feb 23 22:19:43 lenovo sshd[11962]: debug1: session_new: session 0
Feb 23 22:19:43 lenovo sshd[11962]: debug1: session_open: channel 0
Feb 23 22:19:43 lenovo sshd[11962]: debug1: session_open: session 0: link with channel 0
Feb 23 22:19:43 lenovo sshd[11962]: debug1: server_input_channel_open: confirm session
Feb 23 22:19:43 lenovo sshd[11962]: debug1: server_input_channel_req: channel 0 request pty-req reply 1
Feb 23 22:19:43 lenovo sshd[11962]: debug1: session_by_channel: session 0 channel 0
Feb 23 22:19:43 lenovo sshd[11962]: debug1: session_input_channel_req: session 0 req pty-req
Feb 23 22:19:43 lenovo sshd[11962]: debug1: Allocating pty.
Feb 23 22:19:43 lenovo sshd[11947]: debug1: session_new: session 0
Feb 23 22:19:43 lenovo sshd[11947]: debug1: SELinux support enabled
Feb 23 22:19:43 lenovo audit[11947]: USER_LOGIN pid=11947 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=1000 exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=/dev/pts/1 res=success'
Feb 23 22:19:43 lenovo audit[11947]: USER_START pid=11947 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=login id=1000 exe="/usr/sbin/sshd" hostname=192.168.1.116 addr=192.168.1.116 terminal=/dev/pts/1 res=success'
Feb 23 22:19:43 lenovo sshd[11962]: debug1: session_pty_req: session 0 alloc /dev/pts/1
Feb 23 22:19:43 lenovo sshd[11962]: debug1: server_input_channel_req: channel 0 request shell reply 1
Feb 23 22:19:43 lenovo sshd[11962]: debug1: session_by_channel: session 0 channel 0
Feb 23 22:19:43 lenovo sshd[11962]: debug1: session_input_channel_req: session 0 req shell
Feb 23 22:19:43 lenovo sshd[11962]: Starting session: shell on pts/1 for XXXX from 192.168.1.116 port 44743 id 0
Feb 23 22:19:43 lenovo sshd[11969]: debug1: Setting controlling tty using TIOCSCTTY.
Feb 23 22:19:43 lenovo audit[11947]: CRYPTO_KEY_USER pid=11947 uid=0 auid=1000 ses=5 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=SHA256:87:26:e0:66:d1:62:57:5a:c2:9d:44:45:02:8e:1d:2b:0b:92:70:02:d8:e3:41:4d:ae:3a:c5:ef:c5:70:eb:cd direction=? spid=11969 suid=1000  exe="/usr/sbin/sshd" hostname=? addr=192.168.1.116 terminal=? res=success'

**Comment by sjbird** [comment]
Solved.
It is and it isn't.
Turns out that vendors keep dropping support for DSA kays. And apparently Android 7 has dropped it in comparison with Android 6.
Without going into details, I've changed my key from DSA to RSA and it works now.

**Comment by kruton** [comment]
Ah, yes, I've been meaning to put a warning on DSA keys (or maybe remove them entirely). I removed support from Conscrypt a while ago.
