### ISSUE TITLE
FCs when connecting

### ISSUE THREAD

**Issue by hydrian** [connectbot/connectbot#489]
After upgrading to the new material design version, connectbot FCs when ever I start to connect to any host. Hosts that were created pre-upgrade and hosts that were created post-upgrade are effected.

Environment :
Samsung GS6
Android 5.0.2
ConnectBot 1.9.2

**Comment by KurinPawpad** [comment]
I'm also getting force closes on connect attempts, but also when trying to create new connections.  I've attached a logcat recording of a force close on connect attempt.

[connectbot-logcat.txt](https://github.com/connectbot/connectbot/files/799119/connectbot-logcat.txt)

SGS6, Android 5.0.2, ConnectBot 1.9.2

**Comment by hydrian** [comment]
Is there anything we can speed up this fix? I'd hate to move to a different SSH client. I'm dead in the water...

**Comment by kruton** [comment]
I think the problem reported by @KurinPawpad was fixed with b2f66ac649fbd3ddd143d3add46faf345315f9dc. Could you install the version from the releases page? [1.9.2-10](https://github.com/connectbot/connectbot/releases/tag/git-v1.9.2-10-g0a380c1) should work.

**Comment by KurinPawpad** [comment]
git-v1.9.2-10-g0a380c1 fixed connecting to servers added prior to 1.9.2+, but adding new servers in git-v1.9.2-10-g0a380c1 still FCs.

**Comment by kruton** [comment]
Do you have logcat output for that?

**Comment by KurinPawpad** [comment]
Here's a logcat for crashing when clicking the plus button to create a new connection.

[connectbotcrashonnew.txt](https://github.com/connectbot/connectbot/files/803583/connectbotcrashonnew.txt)

SGS6, Android 5.0.2, ConnectBot git-v1.9.2-10-g0a380c1
