### ISSUE TITLE
Ask me to unlock a key instead of skipping it

### ISSUE THREAD

**Issue by ThiefMaster** [connectbot/connectbot#49]
I think the current behavior of going to keyboard-interactive authentication instead of prompting me for the key's passphrase is not very user-friendly. If I have a key chances are good that I want to use it when connecting to a host. Also, AFAIK SSH clients can offer a key's public information to a server to find out if it's going to accept it or not.

So the behavior should be like this:

- If there are no keys, use keyboard-interactive
- Otherwise, offer all keys to the server. If it accepts one, ask for the passphrase to unlock it. If not, proceed to keyboard-interactive.

**Comment by kruton** [comment]
The problem with offering too many keys is that each one counts as an authentication attempt and many servers close the connection after 3 attempts.

**Comment by ThiefMaster** [comment]
There could be an option to select the key which should be used for each server entry.

Anyway, are you sure that querying if a certain key is acceptable (as described on page 8 of the [RFC](http://www.ietf.org/rfc/rfc4252.txt)) "costs" an authentication attempt?

**Comment by leonerd** [comment]
@ThiefMaster there already is an option to set which key is used for each server

**Comment by ThiefMaster** [comment]
Ah indeed. Completely missed that. Nice.
