### ISSUE TITLE
Provide pure floss build flavor

### ISSUE THREAD

**Issue by krt16s** [connectbot/connectbot#490]
A non-free dependency, Google's play-services, got introduced in https://github.com/connectbot/connectbot/commit/159539832f94726fe051648ab8838cb7f8ff9498. Could you provide a build flavor that does not require proprietary libraries?

**Comment by yan12125** [comment]
I guess this issue blocks the update on F-Droid?

**Comment by kruton** [comment]
It will certainly run without Google Play Services, but the `ProviderInstaller` functionality saves several megabytes in binary size while providing new, patched, up-to-date crypto libraries.

**Comment by krt16s** [comment]
@yan12125 : Yes, this blocks fdroids update. 

@kruton:We can flag apps that require non-free stuff installed, but we cannot do anything about apps that require non-free deps at build-time.

**Comment by kruton** [comment]
I put together a product flavor dimension for this and added a dependency on `org.conscrypt:conscrypt-android:1.0.0.RC2`. Here are the size differences:

```
3.6M	app-google-debug.apk
2.7M	app-google-release-unsigned.apk
6.0M	app-oss-debug.apk
5.0M	app-oss-release-unsigned.apk
```

**Comment by krt16s** [comment]
Thanks, builds fine for me.
