### ISSUE TITLE
Home/End/PgUp/PgDn on ASUS TF701T physical keyboard dock don't work.

### ISSUE THREAD

**Issue by Beolach** [connectbot/connectbot#50]
I'm using an ASUS TF701T tablet, with its physical keyboard dock [1], which has a Fn modifier key to change the Left/Right/Up/Down arrow keys into Home/End/PageUp/PageDown keys respectively.  But in ConnectBot v1.8.1 2014.10.21 downloaded here on GitHub, these Home/End/PgUp/PgDn keys don't work - nothing is sent through the SSH connection to the host when I push Fn+Left/Right/Up/Down.  Using them as regular arrow keys (w/out the Fn modifier) works as expected.

Home & End do work correctly in ConnectBot on the username@hostname:port text entry field (PgUp & PgDn are meaningless there) on the bottom of the first screen before opening the SSH connection, but once the SSH connection is open, nothing is sent to the host when pressing these same keys.  Using these keys in either of the IRSSI ConnectBot or VX ConnectBot forks works (although Home & End create different control codes in the 2 forks), but both of those forks have other problems & haven't been updated as recently as ConnectBot, so I'd prefer to keep using ConnectBot.

I test this just by running cat on the SSH host, and then pressing the keys.  I expect this to display control codes similar to the below.  In ConnectBot 1.8.1 the up, down, right, and left control codes (from pressing the keys w/out the Fn modifier) are displayed, and work as expected.  But pressing Home, End, PgUp, and PgDn (using the Fn modifier) does not display anything, and trying to use them in normal operation (not using cat to test) does nothing.

These are the control codes expected.  Up, down, right, & left are displayed, Home, End, PgUp, & PgDn are not:
$ cat
up: ^[[A
down: ^[[B
right: ^[[C
left: ^[[D
Fn+left (Home): ^[[1~ (IRSSI ConnectBot & most SSH clients) or ^[[H (VX ConnectBot)
Fn+right (End): ^[[4~ (IRSSI ConnectBot & most SSH clients) or ^[[F (VX ConnectBot)
Fn+up (PgUp): ^[[5~
Fn+down (PgDown): ^[[6~

Using Terminal Emulator for a local shell on the tablet shows the same control codes as IRSSI ConnectBot.

I have tried changing everything in Settings that I think could be related, to no effect.  This includes all the possible Emulation modes, the Directory shortcuts, and the Shift/Ctrl Fn options.

Let me know if there's any more information I can provide, or anything else I can do to help (I do not have a build environment set up for Android apps).

Thanks in advance,
Beolach

[1]: http://www.newegg.com/Product/Product.aspx?Item=N82E16834989462

**Comment by Beolach** [comment]
One more detail I forget to mention: using the Hacker's Keyboard [1] software on-screen keyboard to send Home/End/PgUp/PgDn through ConnectBot 1.8.1 does work as expected, showing the same control codes as IRSSI ConnectBot.  But I would much prefer using the physical keyboard...

[1]: https://f-droid.org/repository/browse/?fdid=org.pocketworkstation.pckeyboard

**Comment by Beolach** [comment]
Also related to this ASUS TF701T physical keyboard, but more a feature request than a bug report: it would be nice to be able to use the Android Back button as the ESC key.  The top left key, where ESC usually is on PC keyboards, on this keyboard is an Android Back button.  [Terminal IDE] has [1] a toggle option to use the Android Back button as ESC, which works nicely w/ this physical keyboard.

[Terminal IDE]: http://www.spartacusrex.com/terminalide.htm
[1]: https://code.google.com/p/terminal-ide/downloads/list

**Comment by leonerd** [comment]
v1.8.2 adds more supported keys; specifically the Ins/Del/Home/End/PageUp/PageDown block should now be working correctly.

**Comment by Beolach** [comment]
Thank you!  Confirmed working w/ my TF701t physical keyboard dock.

**Comment by arne182** [comment]
Thank you! Also working with my TF700t Physical Keyboard dock.
