### ISSUE TITLE
DSA Key no longer works

### ISSUE THREAD

**Issue by f00bar12** [connectbot/connectbot#500]
Using Connectbot 1.9.2 on a Google Pixel on Android 7.1.1.  When I use an RSA key with a passphrase connecting to a CentOS servers it works, but a DSA key without a passphrase connecting to a Mikrotik router no longer works.  This did work previously and I am unsure if the latest update is what broke this or not.  I used the same key on my PC to connect to the same Mikrotik router and it works fine, and then I downloaded VX Connectbot 1.7.1-29 and it also has no issues connecting using the DSA key.  

Attached is what I see when I try to connect via Connectbot.  Also when I deleted and attempted to reimport the key the key is now renamed with a number instead of the name of the file, which is not what used to happen.

Any help you can give me with this would be greatly appreciated, as I've used Connectbot for years and this is the first real issue I've had with it.

![screenshot_20170303-191801](https://cloud.githubusercontent.com/assets/26175998/23573778/95187f62-0046-11e7-8c2f-a744c80b9cab.png)

**Comment by kruton** [comment]
Can you only use DSA with Microtik? I'm planning on removing DSA completely because it's [horribly insecure](https://github.com/google/wycheproof/blob/master/java/com/google/security/wycheproof/testcases/DsaTest.java#L772) due to (various implementation flaws)[https://github.com/google/wycheproof/blob/master/doc/dsa.md#key-generation].

**Comment by f00bar12** [comment]
Looks like after an update I can use RSA keys on my Mikrotik routers.  Now the only issue I'm having is when I import the keys the name is replaced by a number.  If I have multiple keys this will make things a bit confusing:

![screenshot_20170303-230736](https://cloud.githubusercontent.com/assets/26175998/23575986/4fbdca7e-0066-11e7-8a3d-d2b92e3d69e7.png)

**Comment by pjao** [comment]
Could be possible to add an option to rename the key?

It will be great!

Thanks

**Comment by jbcode42** [comment]
Has anyone started an option to rename the keys? I would not mind trying to code this. (Haven't checked the code in a while so I have to read some code first, just don't want to dupicate work)

**Comment by pjao** [comment]
Issue closed?

If there a way to rename the keys?
