### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by mninc** [connectbot/connectbot#511]
Hi there. I'm a complete noob at Android coding and Android Studio. After a few hours of tinkering, I finally managed to get this app working in Android Studio. What I want to do is have a joystick and a few buttons pop up after the ssh has connected, authenticated and run the post-login automated commands. All these would need to do is input a character. Frankly, I have no idea how to do this: After trawling through lots of the project files, I have found nothing that resembles the position where something like this would go. So what I need is help: What file should this be put in? Is this even possible? How would I do this? Is this way too complicated for me? Is life even worth living?

Thanks

PS. I also don't know how to ask these questions properly. I'm fairly certain this is the wrong place. Sorry.

**Comment by kruton** [comment]
Maybe you actually want to use the [SSH library](https://github.com/connectbot/sshlib/) instead of this app.

**Comment by mninc** [comment]
As I said, I've never really coded apps or anything before with Android. I understand that it would be possible to make what I want without basing it on this app, but I have no idea how I would do this. The idea of using this app as a base is that I don't have to do all of the required complicated things, I can just add a piece of code that I imagine is fairly simple. I would prefer to keep this simple for me, as I don't really know what I am doing. I'm not really intending this as a large project, more of just a slightly messy way to get good, portable controls for something. I can already do this with a PC or this app using WASD, but I would prefer to be able to walk around and not have to fiddle on a small mobile keyboard. Thanks again.

And sorry again.

**Comment by mninc** [comment]
*bump*
