### ISSUE TITLE
Scrolling down is not as smooth as scrolling up

### ISSUE THREAD

**Issue by virtualdj** [connectbot/connectbot#519]
I'm using ConnectBot v1.9.2-50-g94c1907 on a Samsung Galaxy Note 4 with Android KK v4.4.4 and when scrolling long outputs (such as `ls -Rl` output) I noticed that the **text scrolls smoothly when going down** (i.e. when you keep your finger pressed, the text goes fast just by moving the finger a few pixels away).

Unfortunately the same is not true - or at least **it's not the same** - when scrolling **up** (i.e. if you keep the finger pressed you have to travel a longer distance to make the text scroll and it does not scroll continuosly but "in jerks").

![screen](https://cloud.githubusercontent.com/assets/3251704/24722930/d369d27a-1a45-11e7-8846-e38ad33d32da.png)

This is especially noticeable on long history texts: you go quickly up, but not so quickly down.
Here's a [video recorded while scrolling](https://www.dropbox.com/s/bf7pj15v61kvz6v/connectbot_scrolling.mp4?dl=1).

**Comment by JohnVeness** [comment]
I have also noticed this issue, and assumed that the fast scrolling upwards was a bug - certainly it is too fast for me, scrolling up several pages when I just intend to scroll a few lines. And yes, scrolling downwards is very slow.

For me, ideally scrolling should match other apps, e.g. web browsers, where the text moves in sync with the finger, but if the finger flings, it should keep scrolling with some momentum.

It would sometimes also be useful (maybe as an option when defining the scrollback buffer size) to have a usable scrollbar.
