### ISSUE TITLE
URL Scan prefixes http:// incorrectly, causing browser confusion (suggested fix included)

### ISSUE THREAD

**Issue by tsumare** [connectbot/connectbot#521]
In git-v1.9.2-50-g94c1907 (currently the latest available from Releases), when using URL Scan on my Nexus 6X on Android 7, the URL list shows my URLs correctly, but when I select one to launch it, it goes to chrome as "http//www..." without a : after the scheme.  It will keep the scheme itself: "http://" becomes "http//".  "https://" becomes "https//".

After a brief glance at the code, [these lines](https://github.com/connectbot/connectbot/blob/8cf548e559ab82ee9ee15533038b265094c8f733/app/src/main/java/org/connectbot/ConsoleActivity.java#L1188-L1189) may be at fault.  It appears that "http://" is added if there IS a scheme in the url already, rather than if there is NOT.

**Comment by ilf** [comment]
I can confirm this bug. https URLs are opened as http://www.https.com//www.google.com/. #517 is another dupe. Would be cool to merge this pull request. Thanks!
