### ISSUE TITLE
Can't import private ed25519 key

### ISSUE THREAD

**Issue by pejakm** [connectbot/connectbot#53]
Error reported is `Problem parsing imported private key`. Also there is no possibility to generate this type of key. I suppose it's not supported, so if this is the case, please consider adding support for ed25519.

**Comment by ckujau** [comment]
Maybe this report can be merged with https://code.google.com/p/connectbot/issues/detail?id=571 - i.e. upgrade the SSH client stack in ConnectBot?

**Comment by kruton** [comment]
ConnectBot doesn't currently support ed25519, but it is planned.

**Comment by kruton** [comment]
Related to #54

**Comment by kruton** [comment]
Partial support (server-side keys) is available with #370

**Comment by keks** [comment]
Is there some schedule for this? I don't know the codebase but this seems like a low-hanging fruit.

**Comment by funn** [comment]
Also would love to see this implemented.

**Comment by hellyberry** [comment]
Support for Ed25519 would ease load on both clients and servers by better security properties.

**Comment by pejakm** [comment]
It's already done: https://github.com/connectbot/connectbot/commit/adab98f9b95c9c136bfcb720121e26b443406120

Tested and works.
