### ISSUE TITLE
Cannot type non-ascii characters in SSH sessions

### ISSUE THREAD

**Issue by aelmahmoudy** [connectbot/connectbot#542]
I log to a Debian machine using SSH. UTF8 is enabled, usong xterm-256color emulatiin. Yet I cannot type any non-ascii characters in SSH sessions. Even latin characters like é cannot be typed, not to mention arabic characters.
Pasting non-ascii characters sort of works, yet that seems to emit some additional control characters that confuse the input.

**Comment by aelmahmoudy** [comment]
I wonder if #365 is related to this issue

**Comment by aelmahmoudy** [comment]
I found that the problem was with the locale on the remote machine. Setting LANG to en_ US.UTF-8 (or any other utf8 locale I suppose) fixed my issue.

**Comment by jpk-cmd** [comment]
`Ctrl+Shift+u <utf-8code>`

e.g.   "u2234" -> "∴"
