### ISSUE TITLE
Update cyphers

### ISSUE THREAD

**Issue by spikerola** [connectbot/connectbot#557]
Please update cypher to support [this server configuration](https://github.com/drduh/config/blob/master/sshd_config).
Thanks

**Comment by jcdutton** [comment]
This would be really useful to have

**Comment by spikerola** [comment]
So I should just ask [the developers](https://play.google.com/store/apps/developer?id=Kenny+Root,+Jeff+Sharkey,+Torne+Wuff,+Paul+Evans) to update it on the play store.
However termux is what I always searched for so I'm not following anymore this project.
