### ISSUE TITLE
Possible issues with app updates?

### ISSUE THREAD

**Issue by pastcompute** [connectbot/connectbot#56]
Hi,

I am unsure if this is the correct forum:

I had connectbot installed on my rooted Acer Iconia A1-810 tablet which runs Android 4.2.2

Overnight an auto update happened and this triggered Kaspersky on `connectbot ssh-agent-patch` on `HEUR:Trojan-Ransom.AndroidOS.Svpeng.d`

After a very quick google I decided to err on the side of caution and let Kaspersky remove the infected app.  If I had more time I might have tried to grab a copy to provide for forensics for ClamAV. Unfortunately I didn't think to screenshot either :-( I kind of need this tablet to get things done so I had to secure it in a hurry...

The only reference to this malware I could find so far is discussed here: http://forum.dji.com/forum.php?mod=viewthread&tid=7083

This could well be a false positive but I figured you should probably know to do any extra scans as a precaution. For my part I have been running Kaspersky for a few years and never triggered it before

**Comment by gittastic** [comment]
@pastcompute Are you referring to an auto update to Android OS, Kaspersky, or ConnectBot via the Google Play Store?

**Comment by pastcompute** [comment]
OK, I was assuming a couple of things, sorry:

* I installed connectbot quite some time ago (December 2014). Because it is now removed I don't remember if it was installed via GooglePlay or Fdroid (the two stores I use) originally, so I need to add checking that to the list of things to do before allowing the scanner to remove an infected app.

I will try and reinstall it tonight after work

* Kaspersky Internet Security runs on my Android and scans all just-installed or just-updated apps automatically. 

From the above I deduced that connectbot updated itself overnight and then Kaspersky triggered on the newly updated app when it scanned it.

I couldn;t see any obvious log files anywhere to get a better idea of what happened, I will go in tonight and see if I can find any

Connectbot was not running at the time and obviously I did not run it to see what would happen...

**Comment by kruton** [comment]
The "ssh-agent-patch" is a different app on Play Store, so it's possible their account has published something bad.

**Comment by pastcompute** [comment]
doh, sorry :-( I should have spent a bit more time checking further before posting here...
I guess that must be annoying when lots of people build apps from your code!
(AIthough I did figure better to let you know and be wrong!)

Thanks for your help

**Comment by pastcompute** [comment]
For anyone else reading, this is ssh-agent-patch for connectbot

https://github.com/connectbot/connectbot/pull/13
https://play.google.com/store/apps/details?id=com.madgag.ssh.agent&hl=en
