### ISSUE TITLE
Terminal F11 is missing (F10 twice)

### ISSUE THREAD

**Issue by T0biii** [connectbot/connectbot#607]
Hello,
The F11 Button is missing and the F10 Button is there twice.
![Image of F11 is misssing](https://i.tobias.bayern/RVtvuGQL.png)

**Comment by fat-tire** [comment]
What version of CB are you using?  I'm using 1.9.2 and it counts F9, F10, F11, F12 correctly.

**Comment by T0biii** [comment]
#617 + #614
