### ISSUE TITLE
I can open with Android Studio 3.0

### ISSUE THREAD

**Issue by easyboot** [connectbot/connectbot#626]
I Download this project,but I can't Open in Android studio 3.0.
And I Use Connectbot Telnet .but the backspace can't use.how can I do.thank you.

**Comment by easyboot** [comment]
![image](https://user-images.githubusercontent.com/26960023/42927386-f85202b8-8b66-11e8-9c02-0063b86a7822.png)

**Comment by zhangxianweihebei** [comment]
@douglaswth I also have this problem
