### ISSUE TITLE
Android Studio 3.1.4 build error

### ISSUE THREAD

**Issue by kaefert** [connectbot/connectbot#629]
I've imported connectbot into a fresh download & install of Android Studio 3.1.4 and it fails building with this Exception:

```
org.gradle.api.tasks.StopExecutionException: Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.
```

I've tried adding a new line in connectbot/gradle.properies reading `org.gradle.configureondemand=false` but that did not change the build error.

Please help. I'm a complete newbie when it comes to Android development... I would like to implement this feature: https://github.com/connectbot/connectbot/issues/587 but first I need to be able to compile an apk from your sources so that I can start making modifications.

**Comment by jpopovitch** [comment]
From: https://stackoverflow.com/questions/49990933/configuration-on-demand-is-not-supported-by-the-current-version-of-the-android-g

    In Android Studio,
    For Mac go to the Preferences > Build, Execution, Deployment > Compiler and uncheck the configure on demand.
    For Linux/Windows go to the File > Settings > Build, Execution, Deployment > Compiler and uncheck the configure on demand.

hth,

**Comment by kaefert** [comment]
Thank you very much! That worked!

Now it builds the project in a little under two minutes, but I still can't find an apk file anywhere in the project folder..
