### ISSUE TITLE
Imported keys' private key in the wild

### ISSUE THREAD

**Issue by T81** [connectbot/connectbot#636]
Imported OpennSSH keys' private key can be copied without unlocking. 

- Create a set of keys with puttygen
- Secure with passphrase
- Export to OpenSSH format
- Copy to device and import it
- Go to "Manage Public keys" and copy private key without any password prompt

---------
- OS: Win 7
  - puttygen: latest version [link](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)
- Samsung Galaxy S6 edge
  - Android version 7.0
  - connectbot v1.9.2 from google store

**Comment by cinnamonsweets** [comment]
Could it be the passphrase applies only while it is in PPK format and when you export  you are exporting an unprotected OpenSHH format. If you can tap to "lock" and "unlock" that key without a passphrase, then that key has no passphrase. Don't let the picture of a lock fool you. That just symbolizes loading or unloading from memory.

**Comment by visionok** [comment]
Both public and private keys are just plain text. You can copy/view them freely. You only need the passphrase when you use the keys to authenticate.

**Comment by cinnamonsweets** [comment]
Encrypted key in seemingly plain text; you have nothing to worry about. It is still password protected even if they copy it. If you are worried they might copy your encrypted key, you are overthinking it. There are other ways to obtain that encrypted key and it doesn't have to be through connectbot's key management function.

**Comment by T81** [comment]
@visionok this is not true. Only public key is available if key is locked.

**Comment by T81** [comment]
@cinnamonsweets the imported key has retained its passphrase. The awkward is that while it is locked only private key is available for copying, while public is disabled! 
This sounds like a bug to me.
Keys that are created using connectbot have the correct behaviour though. Only public key is available for copying when key is locked.
This **is** a security flow
