### ISSUE TITLE
Fatal Error during MAC startup

### ISSUE THREAD

**Issue by sstidl** [connectbot/connectbot#637]
Using the lastest release from 

https://github.com/connectbot/connectbot/releases/tag/git-v1.9.2-171-g5747c8b6

I get the following message on connect resulting in a failed connection:

Host 'RSA' Schlüssel  bestätigt

Die Verbindung wurde getrennt.
Key exchange was not finished, connection is closed.
Fatal error during MAC startup

**Comment by kruton** [comment]
Does it give any more details? I expanded that particular error in 1.9.2-176. Also details on your host setup would help.

**Comment by gittastic** [comment]
Connection Lost
Key exchange was not finished, connection is closed.
Fatal error during MAC startup!

This is with build 176. Immediate disconnect when trying to ssh to a raspberry pi with standard password ssh setup. I'll try grab some logs later today.

**Comment by kruton** [comment]
Add, this looks like a Proguard issue which is why testing with the debug version doesn't show it. I'll fix this ASAP.

**Comment by gittastic** [comment]
Build 177 fixed it for me. Thanks!

**Comment by sstidl** [comment]
Works now! Thanks for fixing so fast!
