### ISSUE TITLE
color selector ui impossibly small and unusable

### ISSUE THREAD

**Issue by quite** [connectbot/connectbot#64]
On a hammerhead, resolution 1920x1080, the selector looks like this (will attach image). Also, I cannot find a way to type color codes, as an alternative.

**Comment by quite** [comment]
![screenshot_2015-03-27-05-41-48](https://cloud.githubusercontent.com/assets/488679/6862170/9d809b7e-d444-11e4-8add-d472d16c2d1a.png)

**Comment by kruton** [comment]
Here's what it looks like now.
![colors-screen](https://cloud.githubusercontent.com/assets/50407/6876320/32f2857c-d4be-11e4-894d-73077ba0cabc.png)

**Comment by quite** [comment]
Excellent!
