### ISSUE TITLE
MAC algorithms support

### ISSUE THREAD

**Issue by Salokyn** [connectbot/connectbot#647]
Hello,

Connectbot seems not to be working with the folloing MAC (message authentication code) algorithms (available since OpenSSH 6.2) :
- hmac-sha2-512-etm@openssh.com
- hmac-sha2-256-etm@openssh.com
- umac-128-etm@openssh.com

Regards,
Nicolas

**Comment by kruton** [comment]
You didn't mention which version you're using. Currently support is only in the one released on GitHub.

**Comment by Salokyn** [comment]
I'm using the version on Google Play : 1.9.2

**Comment by kruton** [comment]
Okay, it is only in the alpha channel on Google Play currently.
