### ISSUE TITLE
inputType of console, problem with soft keyboard 

### ISSUE THREAD

**Issue by ValZapod** [connectbot/connectbot#665]
![screenshot_20181111-020544_connectbot](https://user-images.githubusercontent.com/31514790/48307136-bd8f4a00-e557-11e8-905e-069147d85a2c.jpg)
I don't know if it was discussed before, but when you open app with inputType:phone and then   open connectbot, type of keyboard is not overwritten to text. So does the enter key (android:imeOptions). You can read about it there: https://developer.android.com/training/keyboard-input/style
I have problems with this in many apps like terminal, material terminal, termux on android 7 and 8.
I suppose the problem is in this code:
```
EditorInfo.IME_FLAG_NO_ENTER_ACTION |
			EditorInfo.IME_ACTION_NONE;
		outAttrs.inputType = EditorInfo.TYPE_NULL;

```

**Comment by ValZapod** [comment]
Also there is a problem when you close the soft keyboard: the text in that case is scrolled to the first line, and you need to press enter or scroll down which is rather annoying.

**Comment by ValZapod** [comment]
@kruton Ping

**Comment by ValZapod** [comment]
@kruton Please can you fix this? It is very disturbing((

**Comment by ValZapod** [comment]
@kruton Please, please fix this, it was bugginb me for a year((

> Also there is a problem when you close the soft keyboard: the text in that case is scrolled to the first line, and you need to press enter or scroll down which is rather annoying.

**Comment by kruton** [comment]
This is a bug in the keyboard as far as I can tell. Most of the complaints have been with Samsung's keyboard.

If I set the type to something different, it has even worse behavior for all keyboards I tested.

**Comment by ValZapod** [comment]
> This is a bug in the keyboard as far as I can tell.

Well, there is no such bug here: https://www.apkmirror.com/apk/samsung-electronics-co-ltd/linux-on-dex-beta/linux-on-dex-beta-1-0-51-release/linux-on-dex-beta-1-0-51-android-apk-download/

Also, you did not understand, 

> Also there is a problem when you close the soft keyboard: the text in that case is scrolled to the first line, and you need to press enter or scroll down which is rather annoying.
