### ISSUE TITLE
Tor/Orbot integration

### ISSUE THREAD

**Issue by sarevok-anchev** [connectbot/connectbot#677]
Congratulations on the recent new release.

Having seen the app pop up on F-Droid, I was curious about checking for connectbot tor support in 2018.

#392 seems to have been forgotten.

Has anything changed two years later, and would it be possible to integrate Orbot with the app?
It would be amazing to access .onion ssh servers using this beautiful app!

**Comment by kruton** [comment]
Thanks for the reminder. Any development will do better in the original issue that you referenced.
