### ISSUE TITLE
Use of insecure key exchange methods defeats the whole purpose of this app

### ISSUE THREAD

**Issue by evernetsoftware** [connectbot/connectbot#681]
I'll keep it short - this app is pointless if it's not completely secure.  The following key exchange methods are all severely outdated:
```
diffie-hellman-group-exchange-sha1
diffie-hellman-group14-sha1
diffie-hellman-group1-sha1
```

SHA1 is 17 years old and has been known to be vulnerable for the last 7 of them.  Using any key exchange method based on this cipher is a complete showstopper for this app.  The interface is quite nice and clearly been updated, yet the defining characteristic of **security** has clearly languished at great peril.  

The degree of effort involved to fix this shortcoming is irrelevant because no one should be using it at all until it happens.  Unfortunately, it would be irresponsible to **NOT** mention this critical issue, so I'll post a review on the Android store but will gladly revise it once this gaping hole is fixed.  Until then, use this at your own peril.

**Comment by kruton** [comment]
I agree with you wholeheartedly that these shouldn't be used and appreciate your vigilence.

However the way algorithm selection in SSH works it will only select this if it's the best that the server supports. ConnectBot orders those at the end of its [list of KEX algorithms](https://github.com/connectbot/sshlib/blob/d2e436769ef992c86ac26f63853731e16277c87e/sshlib/src/main/java/com/trilead/ssh2/transport/KexManager.java#L88) which is what is iterated over when selecting the KEX algorithm.

I've quoted [the relevant section of RFC 4253](https://tools.ietf.org/html/rfc4253#page-13) below for your convenience:

     7.1.  Algorithm Negotiation
     [...]
     kex_algorithms
         Key exchange algorithms were defined above.  The first
         algorithm MUST be the preferred (and guessed) algorithm.  If
         both sides make the same guess, that algorithm MUST be used.
         Otherwise, the following algorithm MUST be used to choose a key
         exchange method: Iterate over client's kex algorithms, one at a
         time.  Choose the first algorithm that satisfies the following
         conditions:

         +  the server also supports the algorithm,

         +  if the algorithm requires an encryption-capable host key,
            there is an encryption-capable algorithm on the server's
            server_host_key_algorithms that is also supported by the
            client, and

         +  if the algorithm requires a signature-capable host key,
            there is a signature-capable algorithm on the server's
            server_host_key_algorithms that is also supported by the
            client.

      If no algorithm satisfying all these conditions can be found, the
      connection fails, and both sides MUST disconnect.

**Comment by evernetsoftware** [comment]
I am aware of how the algorithm is chosen.  My SSH server configuration has been modified precisely to remove the above stated algorithms from the available selection the sever will allow.  The fact that the connection is failing suggests that it is only using the above or more insecure key exchange algos.

The only two that have proven safe thus far are:

`KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256`

If you aren't supporting either of these (especially the second which has been around for years now), then ConnectBot is by essence insecure.  If you are using some other KEX algo besides the three vulnerable ones I mentioned, I'd be happy to know which exactly.

**Comment by kruton** [comment]
It's supported. I already linked you to the location in the code where its preference is set. There are also compatibility tests to [ensure `curve25519-sha256@libssh.org` works with OpenSSH](https://github.com/connectbot/sshlib/blob/master/tests/src/test/java/com/trilead/ssh2/OpenSSHCompatibilityTest.java#L157) and [ensure `curve25519-sha256@libssh.org` works with Dropbear](https://github.com/connectbot/sshlib/blob/master/tests/src/test/java/com/trilead/ssh2/DropbearCompatibilityTest.java#L169).

I imagine it's something else in your configuration that is preventing the connection other than what you're focusing on. If you post the rest of your `sshd_config` I can try to help point it out.
