### ISSUE TITLE
Window size might be incorrect on connect.

### ISSUE THREAD

**Issue by kostikbel** [connectbot/connectbot#70]
I see something strange still with the new version of the connectbot.  When I log in, and re-attach to a screen session which is active in some other terminal (screen -x), initial screen geometry is very wrong.  Full-screen applications like mutt output is garbled.

If I increase and then decrease the font size in connectbot, the display is corrected and full-screen apps work correctly afterward.

**Comment by kruton** [comment]
This might be due to the font scaling based on screen DPI I just added to the last release.

**Comment by kostikbel** [comment]
Apparently, I was wrong, and the fact that the screen session is already attached to another terminal does not matter.  Even for the single-attach, the curses programs display is broken.  It is felt that the display size is off by one, from what I see.

And indeed, the default font size seems to be smaller than it was before the connectbot update.  Before, it was small but acceptable, now it is hard to read.

**Comment by kruton** [comment]
You can use the volume keys to adjust the font.

**Comment by kostikbel** [comment]
Two points.  First, now I *have* to use volume keys, since right after the connection, the display is distorted.  I must increase font size and then decrease it, to get a correct picture. I.e. connected window is broken, after that I do + then -, and the window is now displayed correctly, with the same resolution as after the connect.  Trying to refresh screen from the application (e.g. ^L in mutt) does not help, only resize.

Second, previous version had a useful size, like 80x<something>.  Now it is either 96x38 (too small, and initial screen is distorted), or 68x28, which is less than the 80 columns. assumed by all full-screen software.
