### ISSUE TITLE
Question about storage location for privkey

### ISSUE THREAD

**Issue by MarticusH** [connectbot/connectbot#704]
When generating a private / public keypair, where are those stored locally on the device? I would like to set up an SFTP client on my phone and just re-use the already-generated SSH private key for that (generating an SSH key and being able to place it in the Android filesystem is apparently quite a task).

Thanks!

**Comment by kruton** [comment]
You can't currently view the private keys outside of ConnectBot itself.

**Comment by kruton** [comment]
#378 might be a future solution.
