### ISSUE TITLE
connectbot.org is blocked by hpHosts’ ATS

### ISSUE THREAD

**Issue by DJCrashdummy** [connectbot/connectbot#706]
i'm not sure where else to ask, so hopefully this raises at least some attention...

why is [connectbot.org](https://connectbot.org/) blocked by *hpHosts’ ATS (Ad/tracking servers)*: https://hosts-file.net/default.asp?s=connectbot.org

https://hosts-file.net/?s=classifications
> ATS - Ad/tracking servers
    This classification is assigned for domains being used for advert or tracking purposes 

hopefully this is just a false positive?

**Comment by kruton** [comment]
connectbot.org is hosted on GitHub Pages, so it's possible it's on the list from some association through IP address? I'm not sure because that website doesn't ever respond for me.

**Comment by DJCrashdummy** [comment]
> connectbot.org is hosted on GitHub Pages, so it's possible it's on the list from some association through IP address?

i don't think so... i can't remember of ever having any problem with an other site hosted at GitHub Pages.
in the hpHosts’ ATS-list itself, the whole domain `connectbot.org` is listed and blocked, but no idea why...

> I'm not sure because that website doesn't ever respond for me.

if you are talking about https://hosts-file.net, just retry and wait for it... also for me it takes ages for the site to load, but it works. - don't ask me why.

**Comment by DJCrashdummy** [comment]
just in case added a screenshot:

![hpHosts Online - Simple, Searchable  FREE](https://user-images.githubusercontent.com/26110463/62135084-e1f7a600-b2e1-11e9-85c1-f99376a26ca1.png)
