### ISSUE TITLE
Any other key exchange algorithm options besides rsa-sha2-512?

### ISSUE THREAD

**Issue by zyizhuo** [connectbot/connectbot#713]
`Key exchange was not finished, connection is closed.
The server hostkey was not accepted by the verifier callback
.
Unknown key type rsa-sha2-512`

Any ways to change the algorithm?

**Comment by kruton** [comment]
`rsa-sha2-512` is a signature algorithm, but this should be supported. Could you give more details about the server configuration? What key types are present on the server, configuration for Ciphers, MACs, KexAlgorithms?

**Comment by tessus** [comment]
I have the same problem when trying to connect to both of my QNAP systems.

/etc/ssh/sshd_config
```
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
PermitRootLogin yes
UseDNS no
Subsystem sftp /usr/libexec/sftp-server
AllowTcpForwarding no
```

The only entry in the log is this:

```
Connection closed by x.x.x.x port NNNNN [preauth]
```
