### ISSUE TITLE
it is easy to use

### ISSUE THREAD

**Issue by qidizi** [connectbot/connectbot#78]
please install and have a try。
one ssh client

* it can autoresize，never show new line under the keyboard；

why connectbot not？

* any more easy action。

**Comment by kruton** [comment]
Is this an advertisement?

**Comment by qidizi** [comment]
no，i mean do something maybe it is have one more better way to do 。you  team can have a try。like the auto resize the screen after the vk is show。because it is diffecut by human，resize to 51*25？ohh it is too short。80*25？it is too long too。50*50？the font is small，i can not read 。and ，what size is look like 12PX？i want to resize to smaller，pre size is 80*25？not i am very sure。but i am forget ，how size is it。my mean ，are we is may something to easy to do？
