### ISSUE TITLE
Cursor jumps to the middle of the screen after 2 rotations

### ISSUE THREAD

**Issue by liuyingchao** [connectbot/connectbot#80]
In ConnectBot 1.8.4, after choosing "Automatic" in the "Rotation Mode" setting, you can start at the bottom of a portrait view like in step1.png, then rotate to landscape as in step2.png, and then rotate back to portrait.
You'll notice the cursor moves out of the original place in step 2, and "jumps" to the middle vertically in step 3.

![step1](https://cloud.githubusercontent.com/assets/5846402/7821775/0785cc52-03a6-11e5-8b08-9209a394cc70.png)
![step2](https://cloud.githubusercontent.com/assets/5846402/7821776/0a615d24-03a6-11e5-8f23-581a0fd32016.png)
![step3](https://cloud.githubusercontent.com/assets/5846402/7821780/0d9d8648-03a6-11e5-8a7f-125874d79156.png)

**Comment by liuyingchao** [comment]
@leonerd Paul, Kenny told me you are in charge of terminal emulation. Can you ping me at yingchao.liu@gmail.com? Thanks.

**Comment by jklein24** [comment]
cc @kruton 

This is also easily reproducible by increasing and then decreasing the font size. It seems like something is going wrong with the scroll position when the screen size changes. It's like the whole buffer goes stale in the wrong position.
