### ISSUE TITLE
"Fingerprint changed" message at each connection

### ISSUE THREAD

**Issue by barul42** [connectbot/connectbot#811]
## Bug description
I've got a message saying that my server fingerprint has changed each time I try to SSH into my server (it hasn't, I checked).

## Steps to reproduce
Trying to SSH into a machine.

## Expected behavior
SSHing into the machine without any problem.

## Android device

 - Device: Xiaomi Redmi Note 5 Pro (whyred)
 - OS: LineageOS 17.1 (nightly 20200629)
 - ConnectBot Version: git-v1.9.6-49-g90f78942

## Server information

 - OS: Debian Stable (up-to-date)
 - SSH Software and Version: OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1g
 - Pubkeys used (if applicable): Ed25519

## Additional context
If I downgrade to the previous release (git-v1.9.6-27-g4532c8a8) the problem doesn't happen.

**Comment by gittastic** [comment]
I get same fingerprint warning message since git-v1.9.6-49-g90f78942:

"WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!"

Device: Pixel 4 XL
OS: Android 11 RPB1.200504.020
Connectbot: git-v1.9.6-49-g90f78942
Server: Raspberry Pi OS OpenSSH_7.9p1 Raspbian-10+deb10u2, OpenSSL 1.1.1d

**Comment by kruton** [comment]
Should be fixed with #812
