### ISSUE TITLE
Keys are shown as "Unknown Key Type" or "unknown-bit"

### ISSUE THREAD

**Issue by nyuszika7h** [connectbot/connectbot#83]
It seems pretty much every generated key is shown as "Unknown Key Type". Also, if I import a RSA 4096 key, it's shown as "RSA unknown-bit". The keys still work, though.

**Comment by msoulatre-tt** [comment]
Really easy to fix:
https://github.com/connectbot/connectbot/blob/master/src/org/connectbot/bean/PubkeyBean.java#L170
```
PubkeyUtils.decodePublic(privateKey, type);
```

 should be done with the publicKey instead of the privateKey.

**Comment by kruton** [comment]
Good catch. Will submit that.
