### ISSUE TITLE
Input field missing on Android M preview build MPZ44Q

### ISSUE THREAD

**Issue by gittastic** [connectbot/connectbot#86]
The input field for typing the user@server name is not visible on Connectbot 1.8.4 on Nexus 6 running the M preview build MPZ44Q. I can still type and it works, but can't see what I typed.

Obviously, this is a preview build (so is buggy) of Android, but I remember a similar input issue on L preview too, which was fixed via a Connectbot release, so thought I might as well mention it.

Happy to provide more detail if needed. Many thanks!

![screenshot_20150608-213431](https://cloud.githubusercontent.com/assets/1715371/8033988/eca1a9d4-0e26-11e5-8018-4eb11c740a56.png)

**Comment by tornewuff** [comment]
Huh, so it is. I hadn't noticed because I have a shortcut that goes straight to the only host I ever connect to :)

**Comment by gittastic** [comment]
Yeah, same for me. Have been running the preview for a week and only noticed when I went to connect to a new host.

Out of interest, are the connections backed up to Google by the app (as they reappeared after factory reset) or is it Google just restoring them via it's Android voodoo device restore shenanigans?

**Comment by priitv** [comment]
removing 'android:layout_alignBaseline="@+id/transport_selection"' from act_hostlist.xml layout file (front_quickconnect EditText view) helped me. That line currently doesn't matter there that much.

**Comment by mcnicholls** [comment]
I can second that removing the layout_alignBaseline fixes it for me as well.

**Comment by gittastic** [comment]
FYI - It's worse on M preview 2 MPZ79M as the keyboard doesn't even come up.

![screenshot_20150710-221431](https://cloud.githubusercontent.com/assets/1715371/8618476/371f78bc-2752-11e5-9d69-0ab0d198b5e2.png)

**Comment by kruton** [comment]
Try it with the latest build in releases. I think pull request #91 fixed it.

**Comment by gittastic** [comment]
Yep, it's fixed in latest build. Many thanks!
