### ISSUE TITLE
Keyboard inactive until put in background

### ISSUE THREAD

**Issue by fabriziomazzoni** [connectbot/connectbot#88]
When connecting to a server the keyboard will not work. The solution is to put the program in background and then bring it up again. At this point keyboard will start working correctly and typed words are seen. Happening with HTC one m8 and galaxy s4

**Comment by kruton** [comment]
Some questions to narrow this down:
Do you use password authentication or pubkey?
Is this from a shortcut on the launcher or from the host list in ConnectBot?
Which version are you using?
