### ISSUE TITLE
Support for curve25519-sha256@libssh.org 

### ISSUE THREAD

**Issue by redbaron-gt** [connectbot/connectbot#90]
I set "KexAlgorithms curve25519-sha256@libssh.org" on my servers and now I cant connect with CB.
I get errors "key exchange was not finished, connection is closed. Cannot negotiate, proposals do not match". I have CM 12.1 running on OnePlus One

**Comment by Liath** [comment]
I would also appreciate this.

**Comment by kruton** [comment]
Fixed by #370
