### ISSUE TITLE
Crash on versions git-v1.9.7-76 to git-v1.9.7-82

### ISSUE THREAD

**Issue by gittastic** [connectbot/connectbot#904]
## Bug description
Connectbot crashes when launched on a Pixel 4 XL running latest Android build RQ1A.210205.004.

The affected versions are the latest versions at time of writing:
git-v1.9.7-76-gf2bf38af 
git-v1.9.7-77-g4778931e 
git-v1.9.7-78-g4492a904
git-v1.9.7-79-gbee9ecef
git-v1.9.7-80-g329c8858
git-v1.9.7-81-gd93f5ee4
git-v1.9.7-82-g96664d4c

## Steps to reproduce

1. Open Connectbot
2. Observe instant crash and app close.
3. Try open Connectbot again.
4. See Android dialogue box explaining that "Connectbot keeps stopping".

## Expected behavior

It is expected that Connectbot will open without crashing.

## Android device

 - Device: Google Pixel 4 XL
 - OS: Android 10 build RQ1A.210205.004
 - ConnectBot Versions: git-v1.9.7-77-g4778931e  and git-v1.9.7-76-gf2bf38af and git-v1.9.7-78-g4492a904 and git-v1.9.7-79-gbee9ecef and git-v1.9.7-80-g329c8858 and git-v1.9.7-81-gd93f5ee4 and git-v1.9.7-82-g96664d4c

## Additional context

Thanks for Connectbot!

Edit: Prior version git-v1.9.7-71-gae7366d0  is not affected by this crash bug. The crash was introduced somewhere in this commit: https://github.com/connectbot/connectbot/compare/git-v1.9.7-71-gae7366d0...git-v1.9.7-76-gf2bf38af

**Comment by gittastic** [comment]
Here is the logcat lines with connectbot mentioned. Hopefully it's useful:

`$ ./adb lolcat | grep -i connectbot`

`02-28 09:43:18.760  1593  4624 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.connectbot/.HostListActivity bnds=[594,350][847,643]} from uid 10219
02-28 09:43:18.858  6175  6175 E AndroidRuntime: Process: org.connectbot, PID: 6175
02-28 09:43:18.860  1593  4630 W ActivityTaskManager:   Force finishing activity org.connectbot/.HostListActivity
02-28 09:43:18.902  1593  4630 I WindowManager: WIN DEATH: Window{d682de u0 org.connectbot/org.connectbot.HostListActivity}
02-28 09:43:18.903  1593  4630 W InputDispatcher: Attempted to unregister already unregistered input channel 'd682de org.connectbot/org.connectbot.HostListActivity (server)'
02-28 09:43:18.904  1593  2310 I ActivityManager: Process org.connectbot (pid 6175) has died: fg  TOP 
02-28 09:43:18.913  1593  2310 W ActivityManager: Scheduling restart of crashed service org.connectbot/.service.TerminalManager in 1000ms for start-requested
02-28 09:43:19.361  1593  1622 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{6881dfb u0 org.connectbot/.HostListActivity t-1 f}}
02-28 09:43:19.945  1593  1631 I ActivityManager: Start proc 6272:org.connectbot/u0a244 for service {org.connectbot/org.connectbot.service.TerminalManager}
02-28 09:43:19.951  6272  6272 E org.connectbot: Not starting debugger since process cannot load the jdwp agent.
02-28 09:43:19.958  1593  2310 W ActivityManager: Stopping service due to app idle: u0a244 -1s132ms org.connectbot/.service.TerminalManager
02-28 09:43:20.033  6272  6272 I TetheringManager: registerTetheringEventCallback:org.connectbot
02-28 09:43:20.048  1593  2545 W ActivityManager: Service done with onDestroy, but executeNesting=2: ServiceRecord{680811d u0 org.connectbot/.service.TerminalManager}
02-28 09:43:20.079  6272  6305 I org.connectbot: The ClassLoaderContext is a special shared library.
02-28 09:43:20.087  6272  6305 I org.connectbot: The ClassLoaderContext is a special shared library.
02-28 09:43:24.988  6272  6296 I org.connectbot: Waiting for a blocking GC ProfileSaver
02-28 09:43:25.005  6272  6296 I org.connectbot: WaitForGcToComplete blocked ProfileSaver on ClassLinker for 16.510ms
02-28 09:43:25.016  6272  6287 I org.connectbot: WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 10.709ms
`

**Comment by sppmasterspp** [comment]
Same app crash here.

**Comment by ShevT** [comment]
git-v1.9.7-81

`03-01 16:17:06.632 11318 11318 D AndroidRuntime: Shutting down VM
03-01 16:17:06.632  2543  2543 E coilsw.launche: Invalid ID 0x0000002d.
03-01 16:17:06.632 11318 11318 E AndroidRuntime: FATAL EXCEPTION: main
03-01 16:17:06.632 11318 11318 E AndroidRuntime: Process: org.connectbot, PID: 11318
03-01 16:17:06.632 11318 11318 E AndroidRuntime: java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.AppCompatDelegateImpl$5' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in base.apk)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(ContentFrameLayout.java:3)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.View.dispatchAttachedToWindow(View.java:20626)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3514)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2702)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2182)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8730)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:1049)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1275)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:233)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8010)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
03-01 16:17:06.632 11318 11318 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
03-01 16:17:06.635  1411  5434 W ActivityTaskManager:   Force finishing activity org.connectbot/.HostListActivity
03-01 16:17:06.635  1411 22550 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
03-01 16:17:06.635  1411 22550 D FrameworkEventCollector: recordAppIssue PN: org.connectbot`

**Comment by kruton** [comment]
Huh, I wonder if this is the appcompat libraries. I'll check it out. Thanks for raising this.

**Comment by sppmasterspp** [comment]
git-v1.9.7-82-g96664d4c still a no-go.

**Comment by kruton** [comment]
#905 should fix it from other reports.

**Comment by gittastic** [comment]
git-v1.9.7-83-g525ce6c2 fixed the crash. Thank you!

**Comment by barul42** [comment]
Fixed it for me too, thanks a lot!
