### ISSUE TITLE
virtual keyboard: provide functionality for arrow keys

### ISSUE THREAD

**Issue by ilf** [connectbot/connectbot#96]
For a terminal, arrow key navigation is helpful. VX ConnectBot has a nice virtual keyboard with the four arrows up, down, left and right. I would love to see this in ConnectBot, too.

**Comment by adb2001** [comment]
+1
I'm using google keyboard by default but I'm forced to switch to swiftkey when using connectbot because arrow keys is a must have in bash and vi.

**Comment by jklein24** [comment]
Fixed by https://github.com/connectbot/connectbot/pull/120. Thanks, @alescdb!
